// <auto-generated>
/*
 * x402api Public API
 *
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using X402Api.Client;

namespace X402Api.Model
{
    /// <summary>
    /// ExternalAddressControlCapability
    /// </summary>
    public partial class ExternalAddressControlCapability : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExternalAddressControlCapability" /> class.
        /// </summary>
        /// <param name="network">network</param>
        /// <param name="proofMethods">proofMethods</param>
        [JsonConstructor]
        internal ExternalAddressControlCapability(string network, List<ExternalAddressProofInputMethodEnum> proofMethods)
        {
            Network = network;
            ProofMethods = proofMethods;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Network
        /// </summary>
        [JsonPropertyName("network")]
        public string Network { get; }

        /// <summary>
        /// Gets or Sets ProofMethods
        /// </summary>
        [JsonPropertyName("proof_methods")]
        public List<ExternalAddressProofInputMethodEnum> ProofMethods { get; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ExternalAddressControlCapability {\n");
            sb.Append("  Network: ").Append(Network).Append("\n");
            sb.Append("  ProofMethods: ").Append(ProofMethods).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ExternalAddressControlCapability" />
    /// </summary>
    public partial class ExternalAddressControlCapabilityJsonConverter : JsonConverter<ExternalAddressControlCapability>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ExternalAddressControlCapabilityJsonConverter" /> class.
        /// </summary>
        public ExternalAddressControlCapabilityJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ExternalAddressControlCapability" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ExternalAddressControlCapability Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> network = default;
            Option<List<ExternalAddressProofInputMethodEnum>?> proofMethods = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "network":
                            network = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "proof_methods":
                            proofMethods = new Option<List<ExternalAddressProofInputMethodEnum>?>(JsonSerializer.Deserialize<List<ExternalAddressProofInputMethodEnum>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!network.IsSet)
                throw new ArgumentException("Property is required for class ExternalAddressControlCapability.", nameof(network));

            if (!proofMethods.IsSet)
                throw new ArgumentException("Property is required for class ExternalAddressControlCapability.", nameof(proofMethods));

            if (network.IsSet && network.Value == null)
                throw new ArgumentNullException(nameof(network), "Property is not nullable for class ExternalAddressControlCapability.");

            if (proofMethods.IsSet && proofMethods.Value == null)
                throw new ArgumentNullException(nameof(proofMethods), "Property is not nullable for class ExternalAddressControlCapability.");

            return new ExternalAddressControlCapability(network.Value!, proofMethods.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ExternalAddressControlCapability" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="externalAddressControlCapability"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ExternalAddressControlCapability externalAddressControlCapability, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, externalAddressControlCapability, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ExternalAddressControlCapability" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="externalAddressControlCapability"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ExternalAddressControlCapability externalAddressControlCapability, JsonSerializerOptions jsonSerializerOptions)
        {
            if (externalAddressControlCapability.Network == null)
                throw new ArgumentNullException(nameof(externalAddressControlCapability.Network), "Property is required for class ExternalAddressControlCapability.");

            if (externalAddressControlCapability.ProofMethods == null)
                throw new ArgumentNullException(nameof(externalAddressControlCapability.ProofMethods), "Property is required for class ExternalAddressControlCapability.");

            writer.WriteString("network", externalAddressControlCapability.Network);

            writer.WritePropertyName("proof_methods");
            JsonSerializer.Serialize(writer, externalAddressControlCapability.ProofMethods, jsonSerializerOptions);
        }
    }

    /// <summary>
    /// The ExternalAddressControlCapabilitySerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(ExternalAddressControlCapability))]
    public partial class ExternalAddressControlCapabilitySerializationContext : JsonSerializerContext { }
}
