// <auto-generated>
/*
 * x402api Public API
 *
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using X402Api.Client;

namespace X402Api.Model
{
    /// <summary>
    /// Reject extra or missing JSON keys instead of silently projecting them.
    /// </summary>
    public partial class ExternalAddressControlChallengeCreate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExternalAddressControlChallengeCreate" /> class.
        /// </summary>
        /// <param name="network">network</param>
        /// <param name="assetId">assetId</param>
        /// <param name="address">address</param>
        /// <param name="proofMethod">proofMethod</param>
        [JsonConstructor]
        public ExternalAddressControlChallengeCreate(string network, string assetId, string address, ExternalAddressProofInputMethodEnum proofMethod)
        {
            Network = network;
            AssetId = assetId;
            Address = address;
            ProofMethod = proofMethod;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets ProofMethod
        /// </summary>
        [JsonPropertyName("proof_method")]
        public ExternalAddressProofInputMethodEnum ProofMethod { get; set; }

        /// <summary>
        /// Gets or Sets Network
        /// </summary>
        [JsonPropertyName("network")]
        public string Network { get; set; }

        /// <summary>
        /// Gets or Sets AssetId
        /// </summary>
        [JsonPropertyName("asset_id")]
        public string AssetId { get; set; }

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [JsonPropertyName("address")]
        public string Address { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ExternalAddressControlChallengeCreate {\n");
            sb.Append("  Network: ").Append(Network).Append("\n");
            sb.Append("  AssetId: ").Append(AssetId).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  ProofMethod: ").Append(ProofMethod).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Network (string) maxLength
            if (this.Network != null && this.Network.Length > 80)
            {
                yield return new ValidationResult("Invalid value for Network, length must be less than 80.", new [] { "Network" });
            }

            // AssetId (string) maxLength
            if (this.AssetId != null && this.AssetId.Length > 80)
            {
                yield return new ValidationResult("Invalid value for AssetId, length must be less than 80.", new [] { "AssetId" });
            }

            if (this.AssetId != null) {
                // AssetId (string) pattern
                Regex regexAssetId = new Regex(@"^[-a-zA-Z0-9_]+$", RegexOptions.CultureInvariant);

                if (!regexAssetId.Match(this.AssetId).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for AssetId, must match a pattern of " + regexAssetId, new [] { "AssetId" });
                }
            }

            // Address (string) maxLength
            if (this.Address != null && this.Address.Length > 160)
            {
                yield return new ValidationResult("Invalid value for Address, length must be less than 160.", new [] { "Address" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ExternalAddressControlChallengeCreate" />
    /// </summary>
    public partial class ExternalAddressControlChallengeCreateJsonConverter : JsonConverter<ExternalAddressControlChallengeCreate>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ExternalAddressControlChallengeCreateJsonConverter" /> class.
        /// </summary>
        public ExternalAddressControlChallengeCreateJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ExternalAddressControlChallengeCreate" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ExternalAddressControlChallengeCreate Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> network = default;
            Option<string?> assetId = default;
            Option<string?> address = default;
            Option<ExternalAddressProofInputMethodEnum?> proofMethod = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "network":
                            network = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "asset_id":
                            assetId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "address":
                            address = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "proof_method":
                            proofMethod = new Option<ExternalAddressProofInputMethodEnum?>(JsonSerializer.Deserialize<ExternalAddressProofInputMethodEnum?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!network.IsSet)
                throw new ArgumentException("Property is required for class ExternalAddressControlChallengeCreate.", nameof(network));

            if (!assetId.IsSet)
                throw new ArgumentException("Property is required for class ExternalAddressControlChallengeCreate.", nameof(assetId));

            if (!address.IsSet)
                throw new ArgumentException("Property is required for class ExternalAddressControlChallengeCreate.", nameof(address));

            if (!proofMethod.IsSet)
                throw new ArgumentException("Property is required for class ExternalAddressControlChallengeCreate.", nameof(proofMethod));

            if (network.IsSet && network.Value == null)
                throw new ArgumentNullException(nameof(network), "Property is not nullable for class ExternalAddressControlChallengeCreate.");

            if (assetId.IsSet && assetId.Value == null)
                throw new ArgumentNullException(nameof(assetId), "Property is not nullable for class ExternalAddressControlChallengeCreate.");

            if (address.IsSet && address.Value == null)
                throw new ArgumentNullException(nameof(address), "Property is not nullable for class ExternalAddressControlChallengeCreate.");

            if (proofMethod.IsSet && proofMethod.Value == null)
                throw new ArgumentNullException(nameof(proofMethod), "Property is not nullable for class ExternalAddressControlChallengeCreate.");

            return new ExternalAddressControlChallengeCreate(network.Value!, assetId.Value!, address.Value!, proofMethod.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ExternalAddressControlChallengeCreate" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="externalAddressControlChallengeCreate"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ExternalAddressControlChallengeCreate externalAddressControlChallengeCreate, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, externalAddressControlChallengeCreate, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ExternalAddressControlChallengeCreate" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="externalAddressControlChallengeCreate"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ExternalAddressControlChallengeCreate externalAddressControlChallengeCreate, JsonSerializerOptions jsonSerializerOptions)
        {
            if (externalAddressControlChallengeCreate.Network == null)
                throw new ArgumentNullException(nameof(externalAddressControlChallengeCreate.Network), "Property is required for class ExternalAddressControlChallengeCreate.");

            if (externalAddressControlChallengeCreate.AssetId == null)
                throw new ArgumentNullException(nameof(externalAddressControlChallengeCreate.AssetId), "Property is required for class ExternalAddressControlChallengeCreate.");

            if (externalAddressControlChallengeCreate.Address == null)
                throw new ArgumentNullException(nameof(externalAddressControlChallengeCreate.Address), "Property is required for class ExternalAddressControlChallengeCreate.");

            writer.WriteString("network", externalAddressControlChallengeCreate.Network);

            writer.WriteString("asset_id", externalAddressControlChallengeCreate.AssetId);

            writer.WriteString("address", externalAddressControlChallengeCreate.Address);

            var proofMethodRawValue = ExternalAddressProofInputMethodEnumValueConverter.ToJsonValue(externalAddressControlChallengeCreate.ProofMethod);
            writer.WriteString("proof_method", proofMethodRawValue);
        }
    }

    /// <summary>
    /// The ExternalAddressControlChallengeCreateSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(ExternalAddressControlChallengeCreate))]
    public partial class ExternalAddressControlChallengeCreateSerializationContext : JsonSerializerContext { }
}
