// <auto-generated>
/*
 * x402api Public API
 *
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 1.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using X402Api.Client;

namespace X402Api.Model
{
    /// <summary>
    /// Reject extra or missing JSON keys instead of silently projecting them.
    /// </summary>
    public partial class ExternalAddressControlProofInput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExternalAddressControlProofInput" /> class.
        /// </summary>
        /// <param name="method">method</param>
        /// <param name="signature">signature</param>
        /// <param name="transactionHash">transactionHash</param>
        [JsonConstructor]
        public ExternalAddressControlProofInput(ExternalAddressProofInputMethodEnum method, Option<string?> signature = default, Option<string?> transactionHash = default)
        {
            Method = method;
            SignatureOption = signature;
            TransactionHashOption = transactionHash;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Method
        /// </summary>
        [JsonPropertyName("method")]
        public ExternalAddressProofInputMethodEnum Method { get; set; }

        /// <summary>
        /// Used to track the state of Signature
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SignatureOption { get; private set; }

        /// <summary>
        /// Gets or Sets Signature
        /// </summary>
        [JsonPropertyName("signature")]
        public string? Signature { get { return this.SignatureOption.Value; } set { this.SignatureOption = new(value); } }

        /// <summary>
        /// Used to track the state of TransactionHash
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TransactionHashOption { get; private set; }

        /// <summary>
        /// Gets or Sets TransactionHash
        /// </summary>
        [JsonPropertyName("transaction_hash")]
        public string? TransactionHash { get { return this.TransactionHashOption.Value; } set { this.TransactionHashOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ExternalAddressControlProofInput {\n");
            sb.Append("  Method: ").Append(Method).Append("\n");
            sb.Append("  Signature: ").Append(Signature).Append("\n");
            sb.Append("  TransactionHash: ").Append(TransactionHash).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Signature (string) maxLength
            if (this.Signature != null && this.Signature.Length > 256)
            {
                yield return new ValidationResult("Invalid value for Signature, length must be less than 256.", new [] { "Signature" });
            }

            // TransactionHash (string) maxLength
            if (this.TransactionHash != null && this.TransactionHash.Length > 160)
            {
                yield return new ValidationResult("Invalid value for TransactionHash, length must be less than 160.", new [] { "TransactionHash" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ExternalAddressControlProofInput" />
    /// </summary>
    public partial class ExternalAddressControlProofInputJsonConverter : JsonConverter<ExternalAddressControlProofInput>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ExternalAddressControlProofInputJsonConverter" /> class.
        /// </summary>
        public ExternalAddressControlProofInputJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ExternalAddressControlProofInput" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ExternalAddressControlProofInput Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<ExternalAddressProofInputMethodEnum?> method = default;
            Option<string?> signature = default;
            Option<string?> transactionHash = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "method":
                            method = new Option<ExternalAddressProofInputMethodEnum?>(JsonSerializer.Deserialize<ExternalAddressProofInputMethodEnum?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "signature":
                            signature = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "transaction_hash":
                            transactionHash = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!method.IsSet)
                throw new ArgumentException("Property is required for class ExternalAddressControlProofInput.", nameof(method));

            if (method.IsSet && method.Value == null)
                throw new ArgumentNullException(nameof(method), "Property is not nullable for class ExternalAddressControlProofInput.");

            if (signature.IsSet && signature.Value == null)
                throw new ArgumentNullException(nameof(signature), "Property is not nullable for class ExternalAddressControlProofInput.");

            if (transactionHash.IsSet && transactionHash.Value == null)
                throw new ArgumentNullException(nameof(transactionHash), "Property is not nullable for class ExternalAddressControlProofInput.");

            return new ExternalAddressControlProofInput(method.Value!.Value!, signature, transactionHash);
        }

        /// <summary>
        /// Serializes a <see cref="ExternalAddressControlProofInput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="externalAddressControlProofInput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ExternalAddressControlProofInput externalAddressControlProofInput, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, externalAddressControlProofInput, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ExternalAddressControlProofInput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="externalAddressControlProofInput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ExternalAddressControlProofInput externalAddressControlProofInput, JsonSerializerOptions jsonSerializerOptions)
        {
            if (externalAddressControlProofInput.SignatureOption.IsSet && externalAddressControlProofInput.Signature == null)
                throw new ArgumentNullException(nameof(externalAddressControlProofInput.Signature), "Property is required for class ExternalAddressControlProofInput.");

            if (externalAddressControlProofInput.TransactionHashOption.IsSet && externalAddressControlProofInput.TransactionHash == null)
                throw new ArgumentNullException(nameof(externalAddressControlProofInput.TransactionHash), "Property is required for class ExternalAddressControlProofInput.");

            var methodRawValue = ExternalAddressProofInputMethodEnumValueConverter.ToJsonValue(externalAddressControlProofInput.Method);
            writer.WriteString("method", methodRawValue);

            if (externalAddressControlProofInput.SignatureOption.IsSet)
                writer.WriteString("signature", externalAddressControlProofInput.Signature);

            if (externalAddressControlProofInput.TransactionHashOption.IsSet)
                writer.WriteString("transaction_hash", externalAddressControlProofInput.TransactionHash);
        }
    }

    /// <summary>
    /// The ExternalAddressControlProofInputSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(ExternalAddressControlProofInput))]
    public partial class ExternalAddressControlProofInputSerializationContext : JsonSerializerContext { }
}
