// <auto-generated>
/*
 * x402api Public API
 *
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 1.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using X402Api.Client;

namespace X402Api.Model
{
    /// <summary>
    /// ExternalAddressControlChallenge
    /// </summary>
    public partial class ExternalAddressControlChallenge : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExternalAddressControlChallenge" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="network">network</param>
        /// <param name="assetId">assetId</param>
        /// <param name="addressDisplay">addressDisplay</param>
        /// <param name="proofMethod">proofMethod</param>
        /// <param name="message">message</param>
        /// <param name="challengeDigest">challengeDigest</param>
        /// <param name="expiresAt">expiresAt</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="canaryInstructions">canaryInstructions</param>
        /// <param name="consumedAt">consumedAt</param>
        [JsonConstructor]
        internal ExternalAddressControlChallenge(Guid id, string network, string assetId, string addressDisplay, ExternalAddressProofMethodEnum proofMethod, string message, string challengeDigest, DateTimeOffset expiresAt, DateTimeOffset createdAt, Object? canaryInstructions = default, DateTimeOffset? consumedAt = default)
        {
            Id = id;
            Network = network;
            AssetId = assetId;
            AddressDisplay = addressDisplay;
            ProofMethod = proofMethod;
            Message = message;
            ChallengeDigest = challengeDigest;
            ExpiresAt = expiresAt;
            CreatedAt = createdAt;
            CanaryInstructions = canaryInstructions;
            ConsumedAt = consumedAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets ProofMethod
        /// </summary>
        [JsonPropertyName("proof_method")]
        public ExternalAddressProofMethodEnum ProofMethod { get; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; }

        /// <summary>
        /// Gets or Sets Network
        /// </summary>
        [JsonPropertyName("network")]
        public string Network { get; }

        /// <summary>
        /// Gets or Sets AssetId
        /// </summary>
        [JsonPropertyName("asset_id")]
        public string AssetId { get; }

        /// <summary>
        /// Gets or Sets AddressDisplay
        /// </summary>
        [JsonPropertyName("address_display")]
        public string AddressDisplay { get; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [JsonPropertyName("message")]
        public string Message { get; }

        /// <summary>
        /// Gets or Sets ChallengeDigest
        /// </summary>
        [JsonPropertyName("challenge_digest")]
        public string ChallengeDigest { get; }

        /// <summary>
        /// Gets or Sets ExpiresAt
        /// </summary>
        [JsonPropertyName("expires_at")]
        public DateTimeOffset ExpiresAt { get; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("created_at")]
        public DateTimeOffset CreatedAt { get; }

        /// <summary>
        /// Gets or Sets CanaryInstructions
        /// </summary>
        [JsonPropertyName("canary_instructions")]
        public Object? CanaryInstructions { get; }

        /// <summary>
        /// Gets or Sets ConsumedAt
        /// </summary>
        [JsonPropertyName("consumed_at")]
        public DateTimeOffset? ConsumedAt { get; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ExternalAddressControlChallenge {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Network: ").Append(Network).Append("\n");
            sb.Append("  AssetId: ").Append(AssetId).Append("\n");
            sb.Append("  AddressDisplay: ").Append(AddressDisplay).Append("\n");
            sb.Append("  ProofMethod: ").Append(ProofMethod).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  ChallengeDigest: ").Append(ChallengeDigest).Append("\n");
            sb.Append("  ExpiresAt: ").Append(ExpiresAt).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  CanaryInstructions: ").Append(CanaryInstructions).Append("\n");
            sb.Append("  ConsumedAt: ").Append(ConsumedAt).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ExternalAddressControlChallenge" />
    /// </summary>
    public partial class ExternalAddressControlChallengeJsonConverter : JsonConverter<ExternalAddressControlChallenge>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ExternalAddressControlChallengeJsonConverter" /> class.
        /// </summary>
        public ExternalAddressControlChallengeJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize ExpiresAt
        /// </summary>
        public string ExpiresAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public string CreatedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize ConsumedAt
        /// </summary>
        public string ConsumedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="ExternalAddressControlChallenge" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ExternalAddressControlChallenge Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<string?> network = default;
            Option<string?> assetId = default;
            Option<string?> addressDisplay = default;
            Option<ExternalAddressProofMethodEnum?> proofMethod = default;
            Option<string?> message = default;
            Option<string?> challengeDigest = default;
            Option<DateTimeOffset?> expiresAt = default;
            Option<DateTimeOffset?> createdAt = default;
            Option<Object?> canaryInstructions = default;
            Option<DateTimeOffset?> consumedAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "network":
                            network = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "asset_id":
                            assetId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "address_display":
                            addressDisplay = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "proof_method":
                            proofMethod = new Option<ExternalAddressProofMethodEnum?>(JsonSerializer.Deserialize<ExternalAddressProofMethodEnum?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "challenge_digest":
                            challengeDigest = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "expires_at":
                            expiresAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "created_at":
                            createdAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "canary_instructions":
                            canaryInstructions = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "consumed_at":
                            consumedAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class ExternalAddressControlChallenge.", nameof(id));

            if (!network.IsSet)
                throw new ArgumentException("Property is required for class ExternalAddressControlChallenge.", nameof(network));

            if (!assetId.IsSet)
                throw new ArgumentException("Property is required for class ExternalAddressControlChallenge.", nameof(assetId));

            if (!addressDisplay.IsSet)
                throw new ArgumentException("Property is required for class ExternalAddressControlChallenge.", nameof(addressDisplay));

            if (!proofMethod.IsSet)
                throw new ArgumentException("Property is required for class ExternalAddressControlChallenge.", nameof(proofMethod));

            if (!message.IsSet)
                throw new ArgumentException("Property is required for class ExternalAddressControlChallenge.", nameof(message));

            if (!challengeDigest.IsSet)
                throw new ArgumentException("Property is required for class ExternalAddressControlChallenge.", nameof(challengeDigest));

            if (!expiresAt.IsSet)
                throw new ArgumentException("Property is required for class ExternalAddressControlChallenge.", nameof(expiresAt));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class ExternalAddressControlChallenge.", nameof(createdAt));

            if (!canaryInstructions.IsSet)
                throw new ArgumentException("Property is required for class ExternalAddressControlChallenge.", nameof(canaryInstructions));

            if (!consumedAt.IsSet)
                throw new ArgumentException("Property is required for class ExternalAddressControlChallenge.", nameof(consumedAt));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class ExternalAddressControlChallenge.");

            if (network.IsSet && network.Value == null)
                throw new ArgumentNullException(nameof(network), "Property is not nullable for class ExternalAddressControlChallenge.");

            if (assetId.IsSet && assetId.Value == null)
                throw new ArgumentNullException(nameof(assetId), "Property is not nullable for class ExternalAddressControlChallenge.");

            if (addressDisplay.IsSet && addressDisplay.Value == null)
                throw new ArgumentNullException(nameof(addressDisplay), "Property is not nullable for class ExternalAddressControlChallenge.");

            if (proofMethod.IsSet && proofMethod.Value == null)
                throw new ArgumentNullException(nameof(proofMethod), "Property is not nullable for class ExternalAddressControlChallenge.");

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class ExternalAddressControlChallenge.");

            if (challengeDigest.IsSet && challengeDigest.Value == null)
                throw new ArgumentNullException(nameof(challengeDigest), "Property is not nullable for class ExternalAddressControlChallenge.");

            if (expiresAt.IsSet && expiresAt.Value == null)
                throw new ArgumentNullException(nameof(expiresAt), "Property is not nullable for class ExternalAddressControlChallenge.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class ExternalAddressControlChallenge.");

            return new ExternalAddressControlChallenge(id.Value!.Value!, network.Value!, assetId.Value!, addressDisplay.Value!, proofMethod.Value!.Value!, message.Value!, challengeDigest.Value!, expiresAt.Value!.Value!, createdAt.Value!.Value!, canaryInstructions.Value!, consumedAt.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ExternalAddressControlChallenge" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="externalAddressControlChallenge"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ExternalAddressControlChallenge externalAddressControlChallenge, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, externalAddressControlChallenge, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ExternalAddressControlChallenge" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="externalAddressControlChallenge"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ExternalAddressControlChallenge externalAddressControlChallenge, JsonSerializerOptions jsonSerializerOptions)
        {
            if (externalAddressControlChallenge.Network == null)
                throw new ArgumentNullException(nameof(externalAddressControlChallenge.Network), "Property is required for class ExternalAddressControlChallenge.");

            if (externalAddressControlChallenge.AssetId == null)
                throw new ArgumentNullException(nameof(externalAddressControlChallenge.AssetId), "Property is required for class ExternalAddressControlChallenge.");

            if (externalAddressControlChallenge.AddressDisplay == null)
                throw new ArgumentNullException(nameof(externalAddressControlChallenge.AddressDisplay), "Property is required for class ExternalAddressControlChallenge.");

            if (externalAddressControlChallenge.Message == null)
                throw new ArgumentNullException(nameof(externalAddressControlChallenge.Message), "Property is required for class ExternalAddressControlChallenge.");

            if (externalAddressControlChallenge.ChallengeDigest == null)
                throw new ArgumentNullException(nameof(externalAddressControlChallenge.ChallengeDigest), "Property is required for class ExternalAddressControlChallenge.");

            writer.WriteString("id", externalAddressControlChallenge.Id);

            writer.WriteString("network", externalAddressControlChallenge.Network);

            writer.WriteString("asset_id", externalAddressControlChallenge.AssetId);

            writer.WriteString("address_display", externalAddressControlChallenge.AddressDisplay);

            var proofMethodRawValue = ExternalAddressProofMethodEnumValueConverter.ToJsonValue(externalAddressControlChallenge.ProofMethod);
            writer.WriteString("proof_method", proofMethodRawValue);

            writer.WriteString("message", externalAddressControlChallenge.Message);

            writer.WriteString("challenge_digest", externalAddressControlChallenge.ChallengeDigest);

            writer.WriteString("expires_at", externalAddressControlChallenge.ExpiresAt.ToString(ExpiresAtFormat));

            writer.WriteString("created_at", externalAddressControlChallenge.CreatedAt.ToString(CreatedAtFormat));

            if (externalAddressControlChallenge.CanaryInstructions != null)
            {
                writer.WritePropertyName("canary_instructions");
                JsonSerializer.Serialize(writer, externalAddressControlChallenge.CanaryInstructions, jsonSerializerOptions);
            }
            else
                writer.WriteNull("canary_instructions");
            if (externalAddressControlChallenge.ConsumedAt != null)
                writer.WriteString("consumed_at", externalAddressControlChallenge.ConsumedAt.Value.ToString(ConsumedAtFormat));
            else
                writer.WriteNull("consumed_at");
        }
    }

    /// <summary>
    /// The ExternalAddressControlChallengeSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(ExternalAddressControlChallenge))]
    public partial class ExternalAddressControlChallengeSerializationContext : JsonSerializerContext { }
}
