// <auto-generated>
/*
 * x402api Public API
 *
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using X402Api.Client;

namespace X402Api.Model
{
    /// <summary>
    /// ExternalReceivingAddress
    /// </summary>
    public partial class ExternalReceivingAddress : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExternalReceivingAddress" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="walletId">walletId</param>
        /// <param name="walletVersionId">walletVersionId</param>
        /// <param name="label">label</param>
        /// <param name="network">network</param>
        /// <param name="assetId">assetId</param>
        /// <param name="address">address</param>
        /// <param name="status">status</param>
        /// <param name="readinessState">readinessState</param>
        /// <param name="readinessUsable">readinessUsable</param>
        /// <param name="readinessRefreshEligible">readinessRefreshEligible</param>
        /// <param name="readinessStatus">readinessStatus</param>
        /// <param name="activationEligible">activationEligible</param>
        /// <param name="activationEligibleAt">activationEligibleAt</param>
        /// <param name="verifiedAt">verifiedAt</param>
        /// <param name="expiresAt">expiresAt</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="proofMethod">proofMethod</param>
        /// <param name="proofVerifiedAt">proofVerifiedAt</param>
        /// <param name="activatedAt">activatedAt</param>
        /// <param name="observedBalanceAtomic">observedBalanceAtomic</param>
        [JsonConstructor]
        internal ExternalReceivingAddress(Guid id, Guid walletId, Guid walletVersionId, string label, string network, string assetId, string address, string status, string readinessState, bool readinessUsable, bool readinessRefreshEligible, ReadinessStatusEnum readinessStatus, bool activationEligible, DateTimeOffset activationEligibleAt, DateTimeOffset verifiedAt, DateTimeOffset expiresAt, DateTimeOffset createdAt, ExternalAddressProofInputMethodEnum? proofMethod = default, DateTimeOffset? proofVerifiedAt = default, DateTimeOffset? activatedAt = default, string? observedBalanceAtomic = default)
        {
            Id = id;
            WalletId = walletId;
            WalletVersionId = walletVersionId;
            Label = label;
            Network = network;
            AssetId = assetId;
            Address = address;
            Status = status;
            ReadinessState = readinessState;
            ReadinessUsable = readinessUsable;
            ReadinessRefreshEligible = readinessRefreshEligible;
            ReadinessStatus = readinessStatus;
            ActivationEligible = activationEligible;
            ActivationEligibleAt = activationEligibleAt;
            VerifiedAt = verifiedAt;
            ExpiresAt = expiresAt;
            CreatedAt = createdAt;
            ProofMethod = proofMethod;
            ProofVerifiedAt = proofVerifiedAt;
            ActivatedAt = activatedAt;
            ObservedBalanceAtomic = observedBalanceAtomic;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets ReadinessStatus
        /// </summary>
        [JsonPropertyName("readiness_status")]
        public ReadinessStatusEnum ReadinessStatus { get; }

        /// <summary>
        /// Gets or Sets ProofMethod
        /// </summary>
        [JsonPropertyName("proof_method")]
        public ExternalAddressProofInputMethodEnum? ProofMethod { get; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; }

        /// <summary>
        /// Gets or Sets WalletId
        /// </summary>
        [JsonPropertyName("wallet_id")]
        public Guid WalletId { get; }

        /// <summary>
        /// Gets or Sets WalletVersionId
        /// </summary>
        [JsonPropertyName("wallet_version_id")]
        public Guid WalletVersionId { get; }

        /// <summary>
        /// Gets or Sets Label
        /// </summary>
        [JsonPropertyName("label")]
        public string Label { get; }

        /// <summary>
        /// Gets or Sets Network
        /// </summary>
        [JsonPropertyName("network")]
        public string Network { get; }

        /// <summary>
        /// Gets or Sets AssetId
        /// </summary>
        [JsonPropertyName("asset_id")]
        public string AssetId { get; }

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [JsonPropertyName("address")]
        public string Address { get; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public string Status { get; }

        /// <summary>
        /// Gets or Sets ReadinessState
        /// </summary>
        [JsonPropertyName("readiness_state")]
        public string ReadinessState { get; }

        /// <summary>
        /// Gets or Sets ReadinessUsable
        /// </summary>
        [JsonPropertyName("readiness_usable")]
        public bool ReadinessUsable { get; }

        /// <summary>
        /// Gets or Sets ReadinessRefreshEligible
        /// </summary>
        [JsonPropertyName("readiness_refresh_eligible")]
        public bool ReadinessRefreshEligible { get; }

        /// <summary>
        /// Gets or Sets ActivationEligible
        /// </summary>
        [JsonPropertyName("activation_eligible")]
        public bool ActivationEligible { get; }

        /// <summary>
        /// Gets or Sets ActivationEligibleAt
        /// </summary>
        [JsonPropertyName("activation_eligible_at")]
        public DateTimeOffset ActivationEligibleAt { get; }

        /// <summary>
        /// Gets or Sets VerifiedAt
        /// </summary>
        [JsonPropertyName("verified_at")]
        public DateTimeOffset VerifiedAt { get; }

        /// <summary>
        /// Gets or Sets ExpiresAt
        /// </summary>
        [JsonPropertyName("expires_at")]
        public DateTimeOffset ExpiresAt { get; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("created_at")]
        public DateTimeOffset CreatedAt { get; }

        /// <summary>
        /// Gets or Sets ProofVerifiedAt
        /// </summary>
        [JsonPropertyName("proof_verified_at")]
        public DateTimeOffset? ProofVerifiedAt { get; }

        /// <summary>
        /// Gets or Sets ActivatedAt
        /// </summary>
        [JsonPropertyName("activated_at")]
        public DateTimeOffset? ActivatedAt { get; }

        /// <summary>
        /// Gets or Sets ObservedBalanceAtomic
        /// </summary>
        [JsonPropertyName("observed_balance_atomic")]
        public string? ObservedBalanceAtomic { get; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ExternalReceivingAddress {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  WalletId: ").Append(WalletId).Append("\n");
            sb.Append("  WalletVersionId: ").Append(WalletVersionId).Append("\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("  Network: ").Append(Network).Append("\n");
            sb.Append("  AssetId: ").Append(AssetId).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  ReadinessState: ").Append(ReadinessState).Append("\n");
            sb.Append("  ReadinessUsable: ").Append(ReadinessUsable).Append("\n");
            sb.Append("  ReadinessRefreshEligible: ").Append(ReadinessRefreshEligible).Append("\n");
            sb.Append("  ReadinessStatus: ").Append(ReadinessStatus).Append("\n");
            sb.Append("  ActivationEligible: ").Append(ActivationEligible).Append("\n");
            sb.Append("  ActivationEligibleAt: ").Append(ActivationEligibleAt).Append("\n");
            sb.Append("  VerifiedAt: ").Append(VerifiedAt).Append("\n");
            sb.Append("  ExpiresAt: ").Append(ExpiresAt).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  ProofMethod: ").Append(ProofMethod).Append("\n");
            sb.Append("  ProofVerifiedAt: ").Append(ProofVerifiedAt).Append("\n");
            sb.Append("  ActivatedAt: ").Append(ActivatedAt).Append("\n");
            sb.Append("  ObservedBalanceAtomic: ").Append(ObservedBalanceAtomic).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ExternalReceivingAddress" />
    /// </summary>
    public partial class ExternalReceivingAddressJsonConverter : JsonConverter<ExternalReceivingAddress>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ExternalReceivingAddressJsonConverter" /> class.
        /// </summary>
        public ExternalReceivingAddressJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize ActivationEligibleAt
        /// </summary>
        public string ActivationEligibleAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize VerifiedAt
        /// </summary>
        public string VerifiedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize ExpiresAt
        /// </summary>
        public string ExpiresAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public string CreatedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize ProofVerifiedAt
        /// </summary>
        public string ProofVerifiedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize ActivatedAt
        /// </summary>
        public string ActivatedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="ExternalReceivingAddress" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ExternalReceivingAddress Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<Guid?> walletId = default;
            Option<Guid?> walletVersionId = default;
            Option<string?> label = default;
            Option<string?> network = default;
            Option<string?> assetId = default;
            Option<string?> address = default;
            Option<string?> status = default;
            Option<string?> readinessState = default;
            Option<bool?> readinessUsable = default;
            Option<bool?> readinessRefreshEligible = default;
            Option<ReadinessStatusEnum?> readinessStatus = default;
            Option<bool?> activationEligible = default;
            Option<DateTimeOffset?> activationEligibleAt = default;
            Option<DateTimeOffset?> verifiedAt = default;
            Option<DateTimeOffset?> expiresAt = default;
            Option<DateTimeOffset?> createdAt = default;
            Option<ExternalAddressProofInputMethodEnum?> proofMethod = default;
            Option<DateTimeOffset?> proofVerifiedAt = default;
            Option<DateTimeOffset?> activatedAt = default;
            Option<string?> observedBalanceAtomic = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "wallet_id":
                            walletId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "wallet_version_id":
                            walletVersionId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "label":
                            label = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "network":
                            network = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "asset_id":
                            assetId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "address":
                            address = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "readiness_state":
                            readinessState = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "readiness_usable":
                            readinessUsable = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "readiness_refresh_eligible":
                            readinessRefreshEligible = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "readiness_status":
                            readinessStatus = new Option<ReadinessStatusEnum?>(JsonSerializer.Deserialize<ReadinessStatusEnum?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "activation_eligible":
                            activationEligible = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "activation_eligible_at":
                            activationEligibleAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "verified_at":
                            verifiedAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "expires_at":
                            expiresAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "created_at":
                            createdAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "proof_method":
                            proofMethod = new Option<ExternalAddressProofInputMethodEnum?>(JsonSerializer.Deserialize<ExternalAddressProofInputMethodEnum?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "proof_verified_at":
                            proofVerifiedAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "activated_at":
                            activatedAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "observed_balance_atomic":
                            observedBalanceAtomic = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class ExternalReceivingAddress.", nameof(id));

            if (!walletId.IsSet)
                throw new ArgumentException("Property is required for class ExternalReceivingAddress.", nameof(walletId));

            if (!walletVersionId.IsSet)
                throw new ArgumentException("Property is required for class ExternalReceivingAddress.", nameof(walletVersionId));

            if (!label.IsSet)
                throw new ArgumentException("Property is required for class ExternalReceivingAddress.", nameof(label));

            if (!network.IsSet)
                throw new ArgumentException("Property is required for class ExternalReceivingAddress.", nameof(network));

            if (!assetId.IsSet)
                throw new ArgumentException("Property is required for class ExternalReceivingAddress.", nameof(assetId));

            if (!address.IsSet)
                throw new ArgumentException("Property is required for class ExternalReceivingAddress.", nameof(address));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class ExternalReceivingAddress.", nameof(status));

            if (!readinessState.IsSet)
                throw new ArgumentException("Property is required for class ExternalReceivingAddress.", nameof(readinessState));

            if (!readinessUsable.IsSet)
                throw new ArgumentException("Property is required for class ExternalReceivingAddress.", nameof(readinessUsable));

            if (!readinessRefreshEligible.IsSet)
                throw new ArgumentException("Property is required for class ExternalReceivingAddress.", nameof(readinessRefreshEligible));

            if (!readinessStatus.IsSet)
                throw new ArgumentException("Property is required for class ExternalReceivingAddress.", nameof(readinessStatus));

            if (!activationEligible.IsSet)
                throw new ArgumentException("Property is required for class ExternalReceivingAddress.", nameof(activationEligible));

            if (!activationEligibleAt.IsSet)
                throw new ArgumentException("Property is required for class ExternalReceivingAddress.", nameof(activationEligibleAt));

            if (!verifiedAt.IsSet)
                throw new ArgumentException("Property is required for class ExternalReceivingAddress.", nameof(verifiedAt));

            if (!expiresAt.IsSet)
                throw new ArgumentException("Property is required for class ExternalReceivingAddress.", nameof(expiresAt));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class ExternalReceivingAddress.", nameof(createdAt));

            if (!proofMethod.IsSet)
                throw new ArgumentException("Property is required for class ExternalReceivingAddress.", nameof(proofMethod));

            if (!proofVerifiedAt.IsSet)
                throw new ArgumentException("Property is required for class ExternalReceivingAddress.", nameof(proofVerifiedAt));

            if (!activatedAt.IsSet)
                throw new ArgumentException("Property is required for class ExternalReceivingAddress.", nameof(activatedAt));

            if (!observedBalanceAtomic.IsSet)
                throw new ArgumentException("Property is required for class ExternalReceivingAddress.", nameof(observedBalanceAtomic));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class ExternalReceivingAddress.");

            if (walletId.IsSet && walletId.Value == null)
                throw new ArgumentNullException(nameof(walletId), "Property is not nullable for class ExternalReceivingAddress.");

            if (walletVersionId.IsSet && walletVersionId.Value == null)
                throw new ArgumentNullException(nameof(walletVersionId), "Property is not nullable for class ExternalReceivingAddress.");

            if (label.IsSet && label.Value == null)
                throw new ArgumentNullException(nameof(label), "Property is not nullable for class ExternalReceivingAddress.");

            if (network.IsSet && network.Value == null)
                throw new ArgumentNullException(nameof(network), "Property is not nullable for class ExternalReceivingAddress.");

            if (assetId.IsSet && assetId.Value == null)
                throw new ArgumentNullException(nameof(assetId), "Property is not nullable for class ExternalReceivingAddress.");

            if (address.IsSet && address.Value == null)
                throw new ArgumentNullException(nameof(address), "Property is not nullable for class ExternalReceivingAddress.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class ExternalReceivingAddress.");

            if (readinessState.IsSet && readinessState.Value == null)
                throw new ArgumentNullException(nameof(readinessState), "Property is not nullable for class ExternalReceivingAddress.");

            if (readinessUsable.IsSet && readinessUsable.Value == null)
                throw new ArgumentNullException(nameof(readinessUsable), "Property is not nullable for class ExternalReceivingAddress.");

            if (readinessRefreshEligible.IsSet && readinessRefreshEligible.Value == null)
                throw new ArgumentNullException(nameof(readinessRefreshEligible), "Property is not nullable for class ExternalReceivingAddress.");

            if (readinessStatus.IsSet && readinessStatus.Value == null)
                throw new ArgumentNullException(nameof(readinessStatus), "Property is not nullable for class ExternalReceivingAddress.");

            if (activationEligible.IsSet && activationEligible.Value == null)
                throw new ArgumentNullException(nameof(activationEligible), "Property is not nullable for class ExternalReceivingAddress.");

            if (activationEligibleAt.IsSet && activationEligibleAt.Value == null)
                throw new ArgumentNullException(nameof(activationEligibleAt), "Property is not nullable for class ExternalReceivingAddress.");

            if (verifiedAt.IsSet && verifiedAt.Value == null)
                throw new ArgumentNullException(nameof(verifiedAt), "Property is not nullable for class ExternalReceivingAddress.");

            if (expiresAt.IsSet && expiresAt.Value == null)
                throw new ArgumentNullException(nameof(expiresAt), "Property is not nullable for class ExternalReceivingAddress.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class ExternalReceivingAddress.");

            return new ExternalReceivingAddress(id.Value!.Value!, walletId.Value!.Value!, walletVersionId.Value!.Value!, label.Value!, network.Value!, assetId.Value!, address.Value!, status.Value!, readinessState.Value!, readinessUsable.Value!.Value!, readinessRefreshEligible.Value!.Value!, readinessStatus.Value!.Value!, activationEligible.Value!.Value!, activationEligibleAt.Value!.Value!, verifiedAt.Value!.Value!, expiresAt.Value!.Value!, createdAt.Value!.Value!, proofMethod.Value!, proofVerifiedAt.Value!, activatedAt.Value!, observedBalanceAtomic.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ExternalReceivingAddress" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="externalReceivingAddress"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ExternalReceivingAddress externalReceivingAddress, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, externalReceivingAddress, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ExternalReceivingAddress" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="externalReceivingAddress"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ExternalReceivingAddress externalReceivingAddress, JsonSerializerOptions jsonSerializerOptions)
        {
            if (externalReceivingAddress.Label == null)
                throw new ArgumentNullException(nameof(externalReceivingAddress.Label), "Property is required for class ExternalReceivingAddress.");

            if (externalReceivingAddress.Network == null)
                throw new ArgumentNullException(nameof(externalReceivingAddress.Network), "Property is required for class ExternalReceivingAddress.");

            if (externalReceivingAddress.AssetId == null)
                throw new ArgumentNullException(nameof(externalReceivingAddress.AssetId), "Property is required for class ExternalReceivingAddress.");

            if (externalReceivingAddress.Address == null)
                throw new ArgumentNullException(nameof(externalReceivingAddress.Address), "Property is required for class ExternalReceivingAddress.");

            if (externalReceivingAddress.Status == null)
                throw new ArgumentNullException(nameof(externalReceivingAddress.Status), "Property is required for class ExternalReceivingAddress.");

            if (externalReceivingAddress.ReadinessState == null)
                throw new ArgumentNullException(nameof(externalReceivingAddress.ReadinessState), "Property is required for class ExternalReceivingAddress.");

            writer.WriteString("id", externalReceivingAddress.Id);

            writer.WriteString("wallet_id", externalReceivingAddress.WalletId);

            writer.WriteString("wallet_version_id", externalReceivingAddress.WalletVersionId);

            writer.WriteString("label", externalReceivingAddress.Label);

            writer.WriteString("network", externalReceivingAddress.Network);

            writer.WriteString("asset_id", externalReceivingAddress.AssetId);

            writer.WriteString("address", externalReceivingAddress.Address);

            writer.WriteString("status", externalReceivingAddress.Status);

            writer.WriteString("readiness_state", externalReceivingAddress.ReadinessState);

            writer.WriteBoolean("readiness_usable", externalReceivingAddress.ReadinessUsable);

            writer.WriteBoolean("readiness_refresh_eligible", externalReceivingAddress.ReadinessRefreshEligible);

            var readinessStatusRawValue = ReadinessStatusEnumValueConverter.ToJsonValue(externalReceivingAddress.ReadinessStatus);
            writer.WriteString("readiness_status", readinessStatusRawValue);

            writer.WriteBoolean("activation_eligible", externalReceivingAddress.ActivationEligible);

            writer.WriteString("activation_eligible_at", externalReceivingAddress.ActivationEligibleAt.ToString(ActivationEligibleAtFormat));

            writer.WriteString("verified_at", externalReceivingAddress.VerifiedAt.ToString(VerifiedAtFormat));

            writer.WriteString("expires_at", externalReceivingAddress.ExpiresAt.ToString(ExpiresAtFormat));

            writer.WriteString("created_at", externalReceivingAddress.CreatedAt.ToString(CreatedAtFormat));

            if (externalReceivingAddress.ProofMethod == null)
                writer.WriteNull("proof_method");
            else
            {
                var proofMethodRawValue = ExternalAddressProofInputMethodEnumValueConverter.ToJsonValue(externalReceivingAddress.ProofMethod.Value);
                if (proofMethodRawValue != null)
                    writer.WriteString("proof_method", proofMethodRawValue);
                else
                    writer.WriteNull("proof_method");
            }

            if (externalReceivingAddress.ProofVerifiedAt != null)
                writer.WriteString("proof_verified_at", externalReceivingAddress.ProofVerifiedAt.Value.ToString(ProofVerifiedAtFormat));
            else
                writer.WriteNull("proof_verified_at");

            if (externalReceivingAddress.ActivatedAt != null)
                writer.WriteString("activated_at", externalReceivingAddress.ActivatedAt.Value.ToString(ActivatedAtFormat));
            else
                writer.WriteNull("activated_at");

            if (externalReceivingAddress.ObservedBalanceAtomic != null)
                writer.WriteString("observed_balance_atomic", externalReceivingAddress.ObservedBalanceAtomic);
            else
                writer.WriteNull("observed_balance_atomic");
        }
    }

    /// <summary>
    /// The ExternalReceivingAddressSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(ExternalReceivingAddress))]
    public partial class ExternalReceivingAddressSerializationContext : JsonSerializerContext { }
}
