// <auto-generated>
/*
 * x402api Public API
 *
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using X402Api.Client;

namespace X402Api.Model
{
    /// <summary>
    /// * &#x60;GET&#x60; - GET * &#x60;POST&#x60; - POST * &#x60;PUT&#x60; - PUT * &#x60;PATCH&#x60; - PATCH * &#x60;DELETE&#x60; - DELETE
    /// </summary>
    /// <value>* &#x60;GET&#x60; - GET * &#x60;POST&#x60; - POST * &#x60;PUT&#x60; - PUT * &#x60;PATCH&#x60; - PATCH * &#x60;DELETE&#x60; - DELETE</value>
    public enum HTTPMethodEnum
    {
        /// <summary>
        /// Enum GET for value: GET
        /// </summary>
        GET = 1,

        /// <summary>
        /// Enum POST for value: POST
        /// </summary>
        POST = 2,

        /// <summary>
        /// Enum PUT for value: PUT
        /// </summary>
        PUT = 3,

        /// <summary>
        /// Enum PATCH for value: PATCH
        /// </summary>
        PATCH = 4,

        /// <summary>
        /// Enum DELETE for value: DELETE
        /// </summary>
        DELETE = 5
    }

    /// <summary>
    /// Converts <see cref="HTTPMethodEnum"/> to and from the JSON value
    /// </summary>
    public static class HTTPMethodEnumValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="HTTPMethodEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static HTTPMethodEnum FromString(string value)
        {
            if (value.Equals("GET"))
                return HTTPMethodEnum.GET;

            if (value.Equals("POST"))
                return HTTPMethodEnum.POST;

            if (value.Equals("PUT"))
                return HTTPMethodEnum.PUT;

            if (value.Equals("PATCH"))
                return HTTPMethodEnum.PATCH;

            if (value.Equals("DELETE"))
                return HTTPMethodEnum.DELETE;

            throw new NotImplementedException($"Could not convert value to type HTTPMethodEnum: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="HTTPMethodEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static HTTPMethodEnum? FromStringOrDefault(string value)
        {
            if (value.Equals("GET"))
                return HTTPMethodEnum.GET;

            if (value.Equals("POST"))
                return HTTPMethodEnum.POST;

            if (value.Equals("PUT"))
                return HTTPMethodEnum.PUT;

            if (value.Equals("PATCH"))
                return HTTPMethodEnum.PATCH;

            if (value.Equals("DELETE"))
                return HTTPMethodEnum.DELETE;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="HTTPMethodEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(HTTPMethodEnum value)
        {
            if (value == HTTPMethodEnum.GET)
                return "GET";

            if (value == HTTPMethodEnum.POST)
                return "POST";

            if (value == HTTPMethodEnum.PUT)
                return "PUT";

            if (value == HTTPMethodEnum.PATCH)
                return "PATCH";

            if (value == HTTPMethodEnum.DELETE)
                return "DELETE";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="HTTPMethodEnum"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class HTTPMethodEnumJsonConverter : JsonConverter<HTTPMethodEnum>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override HTTPMethodEnum Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            HTTPMethodEnum? result = rawValue == null
                ? null
                : HTTPMethodEnumValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the HTTPMethodEnum to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="hTTPMethodEnum"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, HTTPMethodEnum hTTPMethodEnum, JsonSerializerOptions options)
        {
            writer.WriteStringValue(HTTPMethodEnumValueConverter.ToJsonValue(hTTPMethodEnum).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="HTTPMethodEnum"/>
    /// </summary>
    public class HTTPMethodEnumNullableJsonConverter : JsonConverter<HTTPMethodEnum?>
    {
        /// <summary>
        /// Returns a HTTPMethodEnum from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override HTTPMethodEnum? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            if (reader.TokenType == JsonTokenType.Null)
                return null;

            string? rawValue = reader.GetString();

            HTTPMethodEnum? result = rawValue == null
                ? null
                : HTTPMethodEnumValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the HTTPMethodEnum to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="hTTPMethodEnum"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, HTTPMethodEnum? hTTPMethodEnum, JsonSerializerOptions options)
        {
            if (hTTPMethodEnum.HasValue)
                writer.WriteStringValue(HTTPMethodEnumValueConverter.ToJsonValue(hTTPMethodEnum.Value).ToString());
            else
                writer.WriteNullValue();
        }
    }


    /// <summary>
    /// The HTTPMethodEnumSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(HTTPMethodEnum))]
    public partial class HTTPMethodEnumSerializationContext : JsonSerializerContext { }
}
