// <auto-generated>
/*
 * x402api Public API
 *
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using X402Api.Client;

namespace X402Api.Model
{
    /// <summary>
    /// NativeUsdObservationEvidence
    /// </summary>
    public partial class NativeUsdObservationEvidence : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NativeUsdObservationEvidence" /> class.
        /// </summary>
        /// <param name="source">source</param>
        /// <param name="nativeUsdQuoteMicros">nativeUsdQuoteMicros</param>
        /// <param name="observedAt">observedAt</param>
        [JsonConstructor]
        public NativeUsdObservationEvidence(string source, string nativeUsdQuoteMicros, DateTimeOffset observedAt)
        {
            Source = source;
            NativeUsdQuoteMicros = nativeUsdQuoteMicros;
            ObservedAt = observedAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Source
        /// </summary>
        [JsonPropertyName("source")]
        public string Source { get; set; }

        /// <summary>
        /// Gets or Sets NativeUsdQuoteMicros
        /// </summary>
        [JsonPropertyName("nativeUsdQuoteMicros")]
        public string NativeUsdQuoteMicros { get; set; }

        /// <summary>
        /// Gets or Sets ObservedAt
        /// </summary>
        [JsonPropertyName("observedAt")]
        public DateTimeOffset ObservedAt { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NativeUsdObservationEvidence {\n");
            sb.Append("  Source: ").Append(Source).Append("\n");
            sb.Append("  NativeUsdQuoteMicros: ").Append(NativeUsdQuoteMicros).Append("\n");
            sb.Append("  ObservedAt: ").Append(ObservedAt).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Source (string) maxLength
            if (this.Source != null && this.Source.Length > 128)
            {
                yield return new ValidationResult("Invalid value for Source, length must be less than 128.", new [] { "Source" });
            }

            // NativeUsdQuoteMicros (string) maxLength
            if (this.NativeUsdQuoteMicros != null && this.NativeUsdQuoteMicros.Length > 78)
            {
                yield return new ValidationResult("Invalid value for NativeUsdQuoteMicros, length must be less than 78.", new [] { "NativeUsdQuoteMicros" });
            }

            if (this.NativeUsdQuoteMicros != null) {
                // NativeUsdQuoteMicros (string) pattern
                Regex regexNativeUsdQuoteMicros = new Regex(@"^[1-9][0-9]*$", RegexOptions.CultureInvariant);

                if (!regexNativeUsdQuoteMicros.Match(this.NativeUsdQuoteMicros).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for NativeUsdQuoteMicros, must match a pattern of " + regexNativeUsdQuoteMicros, new [] { "NativeUsdQuoteMicros" });
                }
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NativeUsdObservationEvidence" />
    /// </summary>
    public partial class NativeUsdObservationEvidenceJsonConverter : JsonConverter<NativeUsdObservationEvidence>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="NativeUsdObservationEvidenceJsonConverter" /> class.
        /// </summary>
        public NativeUsdObservationEvidenceJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize ObservedAt
        /// </summary>
        public string ObservedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="NativeUsdObservationEvidence" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override NativeUsdObservationEvidence Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> source = default;
            Option<string?> nativeUsdQuoteMicros = default;
            Option<DateTimeOffset?> observedAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "source":
                            source = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "nativeUsdQuoteMicros":
                            nativeUsdQuoteMicros = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "observedAt":
                            observedAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!source.IsSet)
                throw new ArgumentException("Property is required for class NativeUsdObservationEvidence.", nameof(source));

            if (!nativeUsdQuoteMicros.IsSet)
                throw new ArgumentException("Property is required for class NativeUsdObservationEvidence.", nameof(nativeUsdQuoteMicros));

            if (!observedAt.IsSet)
                throw new ArgumentException("Property is required for class NativeUsdObservationEvidence.", nameof(observedAt));

            if (source.IsSet && source.Value == null)
                throw new ArgumentNullException(nameof(source), "Property is not nullable for class NativeUsdObservationEvidence.");

            if (nativeUsdQuoteMicros.IsSet && nativeUsdQuoteMicros.Value == null)
                throw new ArgumentNullException(nameof(nativeUsdQuoteMicros), "Property is not nullable for class NativeUsdObservationEvidence.");

            if (observedAt.IsSet && observedAt.Value == null)
                throw new ArgumentNullException(nameof(observedAt), "Property is not nullable for class NativeUsdObservationEvidence.");

            return new NativeUsdObservationEvidence(source.Value!, nativeUsdQuoteMicros.Value!, observedAt.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="NativeUsdObservationEvidence" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="nativeUsdObservationEvidence"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, NativeUsdObservationEvidence nativeUsdObservationEvidence, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, nativeUsdObservationEvidence, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="NativeUsdObservationEvidence" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="nativeUsdObservationEvidence"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, NativeUsdObservationEvidence nativeUsdObservationEvidence, JsonSerializerOptions jsonSerializerOptions)
        {
            if (nativeUsdObservationEvidence.Source == null)
                throw new ArgumentNullException(nameof(nativeUsdObservationEvidence.Source), "Property is required for class NativeUsdObservationEvidence.");

            if (nativeUsdObservationEvidence.NativeUsdQuoteMicros == null)
                throw new ArgumentNullException(nameof(nativeUsdObservationEvidence.NativeUsdQuoteMicros), "Property is required for class NativeUsdObservationEvidence.");

            writer.WriteString("source", nativeUsdObservationEvidence.Source);

            writer.WriteString("nativeUsdQuoteMicros", nativeUsdObservationEvidence.NativeUsdQuoteMicros);

            writer.WriteString("observedAt", nativeUsdObservationEvidence.ObservedAt.ToString(ObservedAtFormat));
        }
    }

    /// <summary>
    /// The NativeUsdObservationEvidenceSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(NativeUsdObservationEvidence))]
    public partial class NativeUsdObservationEvidenceSerializationContext : JsonSerializerContext { }
}
