// <auto-generated>
/*
 * x402api Public API
 *
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using X402Api.Client;

namespace X402Api.Model
{
    /// <summary>
    /// NativeFeeObservationEvidence
    /// </summary>
    public partial class NativeFeeObservationEvidence : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NativeFeeObservationEvidence" /> class.
        /// </summary>
        /// <param name="source">source</param>
        /// <param name="nativeFeeAtomic">nativeFeeAtomic</param>
        /// <param name="observedAt">observedAt</param>
        [JsonConstructor]
        public NativeFeeObservationEvidence(string source, string nativeFeeAtomic, DateTimeOffset observedAt)
        {
            Source = source;
            NativeFeeAtomic = nativeFeeAtomic;
            ObservedAt = observedAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Source
        /// </summary>
        [JsonPropertyName("source")]
        public string Source { get; set; }

        /// <summary>
        /// Gets or Sets NativeFeeAtomic
        /// </summary>
        [JsonPropertyName("nativeFeeAtomic")]
        public string NativeFeeAtomic { get; set; }

        /// <summary>
        /// Gets or Sets ObservedAt
        /// </summary>
        [JsonPropertyName("observedAt")]
        public DateTimeOffset ObservedAt { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NativeFeeObservationEvidence {\n");
            sb.Append("  Source: ").Append(Source).Append("\n");
            sb.Append("  NativeFeeAtomic: ").Append(NativeFeeAtomic).Append("\n");
            sb.Append("  ObservedAt: ").Append(ObservedAt).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Source (string) maxLength
            if (this.Source != null && this.Source.Length > 128)
            {
                yield return new ValidationResult("Invalid value for Source, length must be less than 128.", new [] { "Source" });
            }

            // NativeFeeAtomic (string) maxLength
            if (this.NativeFeeAtomic != null && this.NativeFeeAtomic.Length > 78)
            {
                yield return new ValidationResult("Invalid value for NativeFeeAtomic, length must be less than 78.", new [] { "NativeFeeAtomic" });
            }

            if (this.NativeFeeAtomic != null) {
                // NativeFeeAtomic (string) pattern
                Regex regexNativeFeeAtomic = new Regex(@"^(0|[1-9][0-9]*)$", RegexOptions.CultureInvariant);

                if (!regexNativeFeeAtomic.Match(this.NativeFeeAtomic).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for NativeFeeAtomic, must match a pattern of " + regexNativeFeeAtomic, new [] { "NativeFeeAtomic" });
                }
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NativeFeeObservationEvidence" />
    /// </summary>
    public partial class NativeFeeObservationEvidenceJsonConverter : JsonConverter<NativeFeeObservationEvidence>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="NativeFeeObservationEvidenceJsonConverter" /> class.
        /// </summary>
        public NativeFeeObservationEvidenceJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize ObservedAt
        /// </summary>
        public string ObservedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="NativeFeeObservationEvidence" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override NativeFeeObservationEvidence Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> source = default;
            Option<string?> nativeFeeAtomic = default;
            Option<DateTimeOffset?> observedAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "source":
                            source = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "nativeFeeAtomic":
                            nativeFeeAtomic = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "observedAt":
                            observedAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!source.IsSet)
                throw new ArgumentException("Property is required for class NativeFeeObservationEvidence.", nameof(source));

            if (!nativeFeeAtomic.IsSet)
                throw new ArgumentException("Property is required for class NativeFeeObservationEvidence.", nameof(nativeFeeAtomic));

            if (!observedAt.IsSet)
                throw new ArgumentException("Property is required for class NativeFeeObservationEvidence.", nameof(observedAt));

            if (source.IsSet && source.Value == null)
                throw new ArgumentNullException(nameof(source), "Property is not nullable for class NativeFeeObservationEvidence.");

            if (nativeFeeAtomic.IsSet && nativeFeeAtomic.Value == null)
                throw new ArgumentNullException(nameof(nativeFeeAtomic), "Property is not nullable for class NativeFeeObservationEvidence.");

            if (observedAt.IsSet && observedAt.Value == null)
                throw new ArgumentNullException(nameof(observedAt), "Property is not nullable for class NativeFeeObservationEvidence.");

            return new NativeFeeObservationEvidence(source.Value!, nativeFeeAtomic.Value!, observedAt.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="NativeFeeObservationEvidence" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="nativeFeeObservationEvidence"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, NativeFeeObservationEvidence nativeFeeObservationEvidence, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, nativeFeeObservationEvidence, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="NativeFeeObservationEvidence" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="nativeFeeObservationEvidence"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, NativeFeeObservationEvidence nativeFeeObservationEvidence, JsonSerializerOptions jsonSerializerOptions)
        {
            if (nativeFeeObservationEvidence.Source == null)
                throw new ArgumentNullException(nameof(nativeFeeObservationEvidence.Source), "Property is required for class NativeFeeObservationEvidence.");

            if (nativeFeeObservationEvidence.NativeFeeAtomic == null)
                throw new ArgumentNullException(nameof(nativeFeeObservationEvidence.NativeFeeAtomic), "Property is required for class NativeFeeObservationEvidence.");

            writer.WriteString("source", nativeFeeObservationEvidence.Source);

            writer.WriteString("nativeFeeAtomic", nativeFeeObservationEvidence.NativeFeeAtomic);

            writer.WriteString("observedAt", nativeFeeObservationEvidence.ObservedAt.ToString(ObservedAtFormat));
        }
    }

    /// <summary>
    /// The NativeFeeObservationEvidenceSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(NativeFeeObservationEvidence))]
    public partial class NativeFeeObservationEvidenceSerializationContext : JsonSerializerContext { }
}
