// <auto-generated>
/*
 * x402api Public API
 *
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using X402Api.Client;

namespace X402Api.Model
{
    /// <summary>
    /// Published shape for available and explicitly unavailable fee evidence.
    /// </summary>
    public partial class NetworkFeeEvidence : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NetworkFeeEvidence" /> class.
        /// </summary>
        /// <param name="type">type</param>
        /// <param name="varVersion">varVersion</param>
        /// <param name="network">network</param>
        /// <param name="assetId">assetId</param>
        /// <param name="payloadProfile">payloadProfile</param>
        /// <param name="nativeSymbol">nativeSymbol</param>
        /// <param name="nativeDecimals">nativeDecimals</param>
        /// <param name="nativeFeeObservations">nativeFeeObservations</param>
        /// <param name="nativeUsdObservations">nativeUsdObservations</param>
        /// <param name="expiresAt">expiresAt</param>
        [JsonConstructor]
        public NetworkFeeEvidence(string type, int varVersion, string network, string assetId, string payloadProfile, Option<string?> nativeSymbol = default, Option<int?> nativeDecimals = default, Option<List<NativeFeeObservationEvidence>?> nativeFeeObservations = default, Option<List<NativeUsdObservationEvidence>?> nativeUsdObservations = default, Option<DateTimeOffset?> expiresAt = default)
        {
            Type = type;
            VarVersion = varVersion;
            Network = network;
            AssetId = assetId;
            PayloadProfile = payloadProfile;
            NativeSymbolOption = nativeSymbol;
            NativeDecimalsOption = nativeDecimals;
            NativeFeeObservationsOption = nativeFeeObservations;
            NativeUsdObservationsOption = nativeUsdObservations;
            ExpiresAtOption = expiresAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets VarVersion
        /// </summary>
        [JsonPropertyName("version")]
        public int VarVersion { get; set; }

        /// <summary>
        /// Gets or Sets Network
        /// </summary>
        [JsonPropertyName("network")]
        public string Network { get; set; }

        /// <summary>
        /// Gets or Sets AssetId
        /// </summary>
        [JsonPropertyName("assetId")]
        public string AssetId { get; set; }

        /// <summary>
        /// Gets or Sets PayloadProfile
        /// </summary>
        [JsonPropertyName("payloadProfile")]
        public string PayloadProfile { get; set; }

        /// <summary>
        /// Used to track the state of NativeSymbol
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NativeSymbolOption { get; private set; }

        /// <summary>
        /// Gets or Sets NativeSymbol
        /// </summary>
        [JsonPropertyName("nativeSymbol")]
        public string? NativeSymbol { get { return this.NativeSymbolOption.Value; } set { this.NativeSymbolOption = new(value); } }

        /// <summary>
        /// Used to track the state of NativeDecimals
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> NativeDecimalsOption { get; private set; }

        /// <summary>
        /// Gets or Sets NativeDecimals
        /// </summary>
        [JsonPropertyName("nativeDecimals")]
        public int? NativeDecimals { get { return this.NativeDecimalsOption.Value; } set { this.NativeDecimalsOption = new(value); } }

        /// <summary>
        /// Used to track the state of NativeFeeObservations
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<NativeFeeObservationEvidence>?> NativeFeeObservationsOption { get; private set; }

        /// <summary>
        /// Gets or Sets NativeFeeObservations
        /// </summary>
        [JsonPropertyName("nativeFeeObservations")]
        public List<NativeFeeObservationEvidence>? NativeFeeObservations { get { return this.NativeFeeObservationsOption.Value; } set { this.NativeFeeObservationsOption = new(value); } }

        /// <summary>
        /// Used to track the state of NativeUsdObservations
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<NativeUsdObservationEvidence>?> NativeUsdObservationsOption { get; private set; }

        /// <summary>
        /// Gets or Sets NativeUsdObservations
        /// </summary>
        [JsonPropertyName("nativeUsdObservations")]
        public List<NativeUsdObservationEvidence>? NativeUsdObservations { get { return this.NativeUsdObservationsOption.Value; } set { this.NativeUsdObservationsOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExpiresAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTimeOffset?> ExpiresAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets ExpiresAt
        /// </summary>
        [JsonPropertyName("expiresAt")]
        public DateTimeOffset? ExpiresAt { get { return this.ExpiresAtOption.Value; } set { this.ExpiresAtOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NetworkFeeEvidence {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  VarVersion: ").Append(VarVersion).Append("\n");
            sb.Append("  Network: ").Append(Network).Append("\n");
            sb.Append("  AssetId: ").Append(AssetId).Append("\n");
            sb.Append("  PayloadProfile: ").Append(PayloadProfile).Append("\n");
            sb.Append("  NativeSymbol: ").Append(NativeSymbol).Append("\n");
            sb.Append("  NativeDecimals: ").Append(NativeDecimals).Append("\n");
            sb.Append("  NativeFeeObservations: ").Append(NativeFeeObservations).Append("\n");
            sb.Append("  NativeUsdObservations: ").Append(NativeUsdObservations).Append("\n");
            sb.Append("  ExpiresAt: ").Append(ExpiresAt).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // VarVersion (int) minimum
            if (this.VarVersion < (int)1)
            {
                yield return new ValidationResult("Invalid value for VarVersion, must be a value greater than or equal to 1.", new [] { "VarVersion" });
            }

            // Network (string) maxLength
            if (this.Network != null && this.Network.Length > 80)
            {
                yield return new ValidationResult("Invalid value for Network, length must be less than 80.", new [] { "Network" });
            }

            // AssetId (string) maxLength
            if (this.AssetId != null && this.AssetId.Length > 80)
            {
                yield return new ValidationResult("Invalid value for AssetId, length must be less than 80.", new [] { "AssetId" });
            }

            if (this.AssetId != null) {
                // AssetId (string) pattern
                Regex regexAssetId = new Regex(@"^[-a-zA-Z0-9_]+$", RegexOptions.CultureInvariant);

                if (!regexAssetId.Match(this.AssetId).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for AssetId, must match a pattern of " + regexAssetId, new [] { "AssetId" });
                }
            }

            // PayloadProfile (string) maxLength
            if (this.PayloadProfile != null && this.PayloadProfile.Length > 160)
            {
                yield return new ValidationResult("Invalid value for PayloadProfile, length must be less than 160.", new [] { "PayloadProfile" });
            }

            // NativeSymbol (string) maxLength
            if (this.NativeSymbol != null && this.NativeSymbol.Length > 16)
            {
                yield return new ValidationResult("Invalid value for NativeSymbol, length must be less than 16.", new [] { "NativeSymbol" });
            }

            // NativeDecimals (int) maximum
            if (this.NativeDecimalsOption.IsSet && this.NativeDecimalsOption.Value > (int)30)
            {
                yield return new ValidationResult("Invalid value for NativeDecimals, must be a value less than or equal to 30.", new [] { "NativeDecimals" });
            }

            // NativeDecimals (int) minimum
            if (this.NativeDecimalsOption.IsSet && this.NativeDecimalsOption.Value < (int)0)
            {
                yield return new ValidationResult("Invalid value for NativeDecimals, must be a value greater than or equal to 0.", new [] { "NativeDecimals" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NetworkFeeEvidence" />
    /// </summary>
    public partial class NetworkFeeEvidenceJsonConverter : JsonConverter<NetworkFeeEvidence>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="NetworkFeeEvidenceJsonConverter" /> class.
        /// </summary>
        public NetworkFeeEvidenceJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize ExpiresAt
        /// </summary>
        public string ExpiresAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="NetworkFeeEvidence" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override NetworkFeeEvidence Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> type = default;
            Option<int?> varVersion = default;
            Option<string?> network = default;
            Option<string?> assetId = default;
            Option<string?> payloadProfile = default;
            Option<string?> nativeSymbol = default;
            Option<int?> nativeDecimals = default;
            Option<List<NativeFeeObservationEvidence>?> nativeFeeObservations = default;
            Option<List<NativeUsdObservationEvidence>?> nativeUsdObservations = default;
            Option<DateTimeOffset?> expiresAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "type":
                            type = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "version":
                            varVersion = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "network":
                            network = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "assetId":
                            assetId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "payloadProfile":
                            payloadProfile = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "nativeSymbol":
                            nativeSymbol = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "nativeDecimals":
                            nativeDecimals = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "nativeFeeObservations":
                            nativeFeeObservations = new Option<List<NativeFeeObservationEvidence>?>(JsonSerializer.Deserialize<List<NativeFeeObservationEvidence>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "nativeUsdObservations":
                            nativeUsdObservations = new Option<List<NativeUsdObservationEvidence>?>(JsonSerializer.Deserialize<List<NativeUsdObservationEvidence>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "expiresAt":
                            expiresAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class NetworkFeeEvidence.", nameof(type));

            if (!varVersion.IsSet)
                throw new ArgumentException("Property is required for class NetworkFeeEvidence.", nameof(varVersion));

            if (!network.IsSet)
                throw new ArgumentException("Property is required for class NetworkFeeEvidence.", nameof(network));

            if (!assetId.IsSet)
                throw new ArgumentException("Property is required for class NetworkFeeEvidence.", nameof(assetId));

            if (!payloadProfile.IsSet)
                throw new ArgumentException("Property is required for class NetworkFeeEvidence.", nameof(payloadProfile));

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class NetworkFeeEvidence.");

            if (varVersion.IsSet && varVersion.Value == null)
                throw new ArgumentNullException(nameof(varVersion), "Property is not nullable for class NetworkFeeEvidence.");

            if (network.IsSet && network.Value == null)
                throw new ArgumentNullException(nameof(network), "Property is not nullable for class NetworkFeeEvidence.");

            if (assetId.IsSet && assetId.Value == null)
                throw new ArgumentNullException(nameof(assetId), "Property is not nullable for class NetworkFeeEvidence.");

            if (payloadProfile.IsSet && payloadProfile.Value == null)
                throw new ArgumentNullException(nameof(payloadProfile), "Property is not nullable for class NetworkFeeEvidence.");

            if (nativeSymbol.IsSet && nativeSymbol.Value == null)
                throw new ArgumentNullException(nameof(nativeSymbol), "Property is not nullable for class NetworkFeeEvidence.");

            if (nativeDecimals.IsSet && nativeDecimals.Value == null)
                throw new ArgumentNullException(nameof(nativeDecimals), "Property is not nullable for class NetworkFeeEvidence.");

            if (nativeFeeObservations.IsSet && nativeFeeObservations.Value == null)
                throw new ArgumentNullException(nameof(nativeFeeObservations), "Property is not nullable for class NetworkFeeEvidence.");

            if (nativeUsdObservations.IsSet && nativeUsdObservations.Value == null)
                throw new ArgumentNullException(nameof(nativeUsdObservations), "Property is not nullable for class NetworkFeeEvidence.");

            if (expiresAt.IsSet && expiresAt.Value == null)
                throw new ArgumentNullException(nameof(expiresAt), "Property is not nullable for class NetworkFeeEvidence.");

            return new NetworkFeeEvidence(type.Value!, varVersion.Value!.Value!, network.Value!, assetId.Value!, payloadProfile.Value!, nativeSymbol, nativeDecimals, nativeFeeObservations, nativeUsdObservations, expiresAt);
        }

        /// <summary>
        /// Serializes a <see cref="NetworkFeeEvidence" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="networkFeeEvidence"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, NetworkFeeEvidence networkFeeEvidence, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, networkFeeEvidence, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="NetworkFeeEvidence" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="networkFeeEvidence"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, NetworkFeeEvidence networkFeeEvidence, JsonSerializerOptions jsonSerializerOptions)
        {
            if (networkFeeEvidence.Type == null)
                throw new ArgumentNullException(nameof(networkFeeEvidence.Type), "Property is required for class NetworkFeeEvidence.");

            if (networkFeeEvidence.Network == null)
                throw new ArgumentNullException(nameof(networkFeeEvidence.Network), "Property is required for class NetworkFeeEvidence.");

            if (networkFeeEvidence.AssetId == null)
                throw new ArgumentNullException(nameof(networkFeeEvidence.AssetId), "Property is required for class NetworkFeeEvidence.");

            if (networkFeeEvidence.PayloadProfile == null)
                throw new ArgumentNullException(nameof(networkFeeEvidence.PayloadProfile), "Property is required for class NetworkFeeEvidence.");

            if (networkFeeEvidence.NativeSymbolOption.IsSet && networkFeeEvidence.NativeSymbol == null)
                throw new ArgumentNullException(nameof(networkFeeEvidence.NativeSymbol), "Property is required for class NetworkFeeEvidence.");

            if (networkFeeEvidence.NativeFeeObservationsOption.IsSet && networkFeeEvidence.NativeFeeObservations == null)
                throw new ArgumentNullException(nameof(networkFeeEvidence.NativeFeeObservations), "Property is required for class NetworkFeeEvidence.");

            if (networkFeeEvidence.NativeUsdObservationsOption.IsSet && networkFeeEvidence.NativeUsdObservations == null)
                throw new ArgumentNullException(nameof(networkFeeEvidence.NativeUsdObservations), "Property is required for class NetworkFeeEvidence.");

            writer.WriteString("type", networkFeeEvidence.Type);

            writer.WriteNumber("version", networkFeeEvidence.VarVersion);

            writer.WriteString("network", networkFeeEvidence.Network);

            writer.WriteString("assetId", networkFeeEvidence.AssetId);

            writer.WriteString("payloadProfile", networkFeeEvidence.PayloadProfile);

            if (networkFeeEvidence.NativeSymbolOption.IsSet)
                writer.WriteString("nativeSymbol", networkFeeEvidence.NativeSymbol);

            if (networkFeeEvidence.NativeDecimalsOption.IsSet)
                writer.WriteNumber("nativeDecimals", networkFeeEvidence.NativeDecimalsOption.Value!.Value);

            if (networkFeeEvidence.NativeFeeObservationsOption.IsSet)
            {
                writer.WritePropertyName("nativeFeeObservations");
                JsonSerializer.Serialize(writer, networkFeeEvidence.NativeFeeObservations, jsonSerializerOptions);
            }
            if (networkFeeEvidence.NativeUsdObservationsOption.IsSet)
            {
                writer.WritePropertyName("nativeUsdObservations");
                JsonSerializer.Serialize(writer, networkFeeEvidence.NativeUsdObservations, jsonSerializerOptions);
            }
            if (networkFeeEvidence.ExpiresAtOption.IsSet)
                writer.WriteString("expiresAt", networkFeeEvidence.ExpiresAtOption.Value!.Value.ToString(ExpiresAtFormat));
        }
    }

    /// <summary>
    /// The NetworkFeeEvidenceSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(NetworkFeeEvidence))]
    public partial class NetworkFeeEvidenceSerializationContext : JsonSerializerContext { }
}
