// <auto-generated>
/*
 * x402api Public API
 *
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using X402Api.Client;

namespace X402Api.Model
{
    /// <summary>
    /// NetworkFeePreview
    /// </summary>
    public partial class NetworkFeePreview : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NetworkFeePreview" /> class.
        /// </summary>
        /// <param name="prices">prices</param>
        /// <param name="feeMode">feeMode</param>
        /// <param name="quoteCurrency">quoteCurrency</param>
        /// <param name="feeAllowanceCapQuoteMicros">feeAllowanceCapQuoteMicros (default to &quot;0&quot;)</param>
        [JsonConstructor]
        public NetworkFeePreview(List<NetworkFeePreviewPrice> prices, Option<FeePolicyModeInputEnum?> feeMode = default, Option<FeePolicyQuoteCurrencyInputEnum?> quoteCurrency = default, Option<string?> feeAllowanceCapQuoteMicros = default)
        {
            Prices = prices;
            FeeModeOption = feeMode;
            QuoteCurrencyOption = quoteCurrency;
            FeeAllowanceCapQuoteMicrosOption = feeAllowanceCapQuoteMicros;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of FeeMode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<FeePolicyModeInputEnum?> FeeModeOption { get; private set; }

        /// <summary>
        /// Gets or Sets FeeMode
        /// </summary>
        [JsonPropertyName("fee_mode")]
        public FeePolicyModeInputEnum? FeeMode { get { return this.FeeModeOption.Value; } set { this.FeeModeOption = new(value); } }

        /// <summary>
        /// Used to track the state of QuoteCurrency
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<FeePolicyQuoteCurrencyInputEnum?> QuoteCurrencyOption { get; private set; }

        /// <summary>
        /// Gets or Sets QuoteCurrency
        /// </summary>
        [JsonPropertyName("quote_currency")]
        public FeePolicyQuoteCurrencyInputEnum? QuoteCurrency { get { return this.QuoteCurrencyOption.Value; } set { this.QuoteCurrencyOption = new(value); } }

        /// <summary>
        /// Gets or Sets Prices
        /// </summary>
        [JsonPropertyName("prices")]
        public List<NetworkFeePreviewPrice> Prices { get; set; }

        /// <summary>
        /// Used to track the state of FeeAllowanceCapQuoteMicros
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FeeAllowanceCapQuoteMicrosOption { get; private set; }

        /// <summary>
        /// Gets or Sets FeeAllowanceCapQuoteMicros
        /// </summary>
        [JsonPropertyName("fee_allowance_cap_quote_micros")]
        public string? FeeAllowanceCapQuoteMicros { get { return this.FeeAllowanceCapQuoteMicrosOption.Value; } set { this.FeeAllowanceCapQuoteMicrosOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NetworkFeePreview {\n");
            sb.Append("  Prices: ").Append(Prices).Append("\n");
            sb.Append("  FeeMode: ").Append(FeeMode).Append("\n");
            sb.Append("  QuoteCurrency: ").Append(QuoteCurrency).Append("\n");
            sb.Append("  FeeAllowanceCapQuoteMicros: ").Append(FeeAllowanceCapQuoteMicros).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // FeeAllowanceCapQuoteMicros (string) maxLength
            if (this.FeeAllowanceCapQuoteMicros != null && this.FeeAllowanceCapQuoteMicros.Length > 78)
            {
                yield return new ValidationResult("Invalid value for FeeAllowanceCapQuoteMicros, length must be less than 78.", new [] { "FeeAllowanceCapQuoteMicros" });
            }

            if (this.FeeAllowanceCapQuoteMicrosOption.Value != null) {
                // FeeAllowanceCapQuoteMicros (string) pattern
                Regex regexFeeAllowanceCapQuoteMicros = new Regex(@"^(0|[1-9][0-9]*)$", RegexOptions.CultureInvariant);

                if (this.FeeAllowanceCapQuoteMicrosOption.Value != null &&!regexFeeAllowanceCapQuoteMicros.Match(this.FeeAllowanceCapQuoteMicrosOption.Value).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for FeeAllowanceCapQuoteMicros, must match a pattern of " + regexFeeAllowanceCapQuoteMicros, new [] { "FeeAllowanceCapQuoteMicros" });
                }
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NetworkFeePreview" />
    /// </summary>
    public partial class NetworkFeePreviewJsonConverter : JsonConverter<NetworkFeePreview>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="NetworkFeePreviewJsonConverter" /> class.
        /// </summary>
        public NetworkFeePreviewJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="NetworkFeePreview" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override NetworkFeePreview Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<NetworkFeePreviewPrice>?> prices = default;
            Option<FeePolicyModeInputEnum?> feeMode = default;
            Option<FeePolicyQuoteCurrencyInputEnum?> quoteCurrency = default;
            Option<string?> feeAllowanceCapQuoteMicros = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "prices":
                            prices = new Option<List<NetworkFeePreviewPrice>?>(JsonSerializer.Deserialize<List<NetworkFeePreviewPrice>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "fee_mode":
                            feeMode = new Option<FeePolicyModeInputEnum?>(JsonSerializer.Deserialize<FeePolicyModeInputEnum?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "quote_currency":
                            quoteCurrency = new Option<FeePolicyQuoteCurrencyInputEnum?>(JsonSerializer.Deserialize<FeePolicyQuoteCurrencyInputEnum?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "fee_allowance_cap_quote_micros":
                            feeAllowanceCapQuoteMicros = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!prices.IsSet)
                throw new ArgumentException("Property is required for class NetworkFeePreview.", nameof(prices));

            if (prices.IsSet && prices.Value == null)
                throw new ArgumentNullException(nameof(prices), "Property is not nullable for class NetworkFeePreview.");

            if (feeMode.IsSet && feeMode.Value == null)
                throw new ArgumentNullException(nameof(feeMode), "Property is not nullable for class NetworkFeePreview.");

            if (quoteCurrency.IsSet && quoteCurrency.Value == null)
                throw new ArgumentNullException(nameof(quoteCurrency), "Property is not nullable for class NetworkFeePreview.");

            if (feeAllowanceCapQuoteMicros.IsSet && feeAllowanceCapQuoteMicros.Value == null)
                throw new ArgumentNullException(nameof(feeAllowanceCapQuoteMicros), "Property is not nullable for class NetworkFeePreview.");

            return new NetworkFeePreview(prices.Value!, feeMode, quoteCurrency, feeAllowanceCapQuoteMicros);
        }

        /// <summary>
        /// Serializes a <see cref="NetworkFeePreview" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="networkFeePreview"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, NetworkFeePreview networkFeePreview, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, networkFeePreview, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="NetworkFeePreview" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="networkFeePreview"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, NetworkFeePreview networkFeePreview, JsonSerializerOptions jsonSerializerOptions)
        {
            if (networkFeePreview.Prices == null)
                throw new ArgumentNullException(nameof(networkFeePreview.Prices), "Property is required for class NetworkFeePreview.");

            if (networkFeePreview.FeeAllowanceCapQuoteMicrosOption.IsSet && networkFeePreview.FeeAllowanceCapQuoteMicros == null)
                throw new ArgumentNullException(nameof(networkFeePreview.FeeAllowanceCapQuoteMicros), "Property is required for class NetworkFeePreview.");

            writer.WritePropertyName("prices");
            JsonSerializer.Serialize(writer, networkFeePreview.Prices, jsonSerializerOptions);
            if (networkFeePreview.FeeModeOption.IsSet)
            {
                var feeModeRawValue = FeePolicyModeInputEnumValueConverter.ToJsonValue(networkFeePreview.FeeMode!.Value);
                writer.WriteString("fee_mode", feeModeRawValue);
            }
            if (networkFeePreview.QuoteCurrencyOption.IsSet)
            {
                var quoteCurrencyRawValue = FeePolicyQuoteCurrencyInputEnumValueConverter.ToJsonValue(networkFeePreview.QuoteCurrency!.Value);
                writer.WriteString("quote_currency", quoteCurrencyRawValue);
            }
            if (networkFeePreview.FeeAllowanceCapQuoteMicrosOption.IsSet)
                writer.WriteString("fee_allowance_cap_quote_micros", networkFeePreview.FeeAllowanceCapQuoteMicros);
        }
    }

    /// <summary>
    /// The NetworkFeePreviewSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(NetworkFeePreview))]
    public partial class NetworkFeePreviewSerializationContext : JsonSerializerContext { }
}
