// <auto-generated>
/*
 * x402api Public API
 *
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using X402Api.Client;

namespace X402Api.Model
{
    /// <summary>
    /// ObservationBlock
    /// </summary>
    public partial class ObservationBlock : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ObservationBlock" /> class.
        /// </summary>
        /// <param name="number">number</param>
        /// <param name="hash">hash</param>
        /// <param name="finality">finality</param>
        [JsonConstructor]
        public ObservationBlock(string number, string hash, string finality)
        {
            Number = number;
            Hash = hash;
            Finality = finality;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Number
        /// </summary>
        [JsonPropertyName("number")]
        public string Number { get; set; }

        /// <summary>
        /// Gets or Sets Hash
        /// </summary>
        [JsonPropertyName("hash")]
        public string Hash { get; set; }

        /// <summary>
        /// Gets or Sets Finality
        /// </summary>
        [JsonPropertyName("finality")]
        public string Finality { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ObservationBlock {\n");
            sb.Append("  Number: ").Append(Number).Append("\n");
            sb.Append("  Hash: ").Append(Hash).Append("\n");
            sb.Append("  Finality: ").Append(Finality).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ObservationBlock" />
    /// </summary>
    public partial class ObservationBlockJsonConverter : JsonConverter<ObservationBlock>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ObservationBlockJsonConverter" /> class.
        /// </summary>
        public ObservationBlockJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ObservationBlock" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ObservationBlock Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> number = default;
            Option<string?> hash = default;
            Option<string?> finality = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "number":
                            number = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "hash":
                            hash = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "finality":
                            finality = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!number.IsSet)
                throw new ArgumentException("Property is required for class ObservationBlock.", nameof(number));

            if (!hash.IsSet)
                throw new ArgumentException("Property is required for class ObservationBlock.", nameof(hash));

            if (!finality.IsSet)
                throw new ArgumentException("Property is required for class ObservationBlock.", nameof(finality));

            if (number.IsSet && number.Value == null)
                throw new ArgumentNullException(nameof(number), "Property is not nullable for class ObservationBlock.");

            if (hash.IsSet && hash.Value == null)
                throw new ArgumentNullException(nameof(hash), "Property is not nullable for class ObservationBlock.");

            if (finality.IsSet && finality.Value == null)
                throw new ArgumentNullException(nameof(finality), "Property is not nullable for class ObservationBlock.");

            return new ObservationBlock(number.Value!, hash.Value!, finality.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ObservationBlock" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="observationBlock"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ObservationBlock observationBlock, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, observationBlock, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ObservationBlock" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="observationBlock"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ObservationBlock observationBlock, JsonSerializerOptions jsonSerializerOptions)
        {
            if (observationBlock.Number == null)
                throw new ArgumentNullException(nameof(observationBlock.Number), "Property is required for class ObservationBlock.");

            if (observationBlock.Hash == null)
                throw new ArgumentNullException(nameof(observationBlock.Hash), "Property is required for class ObservationBlock.");

            if (observationBlock.Finality == null)
                throw new ArgumentNullException(nameof(observationBlock.Finality), "Property is required for class ObservationBlock.");

            writer.WriteString("number", observationBlock.Number);

            writer.WriteString("hash", observationBlock.Hash);

            writer.WriteString("finality", observationBlock.Finality);
        }
    }

    /// <summary>
    /// The ObservationBlockSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(ObservationBlock))]
    public partial class ObservationBlockSerializationContext : JsonSerializerContext { }
}
