// <auto-generated>
/*
 * x402api Public API
 *
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using X402Api.Client;

namespace X402Api.Model
{
    /// <summary>
    /// PaymentReadiness
    /// </summary>
    public partial class PaymentReadiness : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentReadiness" /> class.
        /// </summary>
        /// <param name="observedAt">observedAt</param>
        /// <param name="tenantStatus">tenantStatus</param>
        /// <param name="tenantAcceptingNewChallenges">tenantAcceptingNewChallenges</param>
        /// <param name="globalChallengesEnabled">globalChallengesEnabled</param>
        /// <param name="globalSettlementEnabled">globalSettlementEnabled</param>
        /// <param name="controlPlaneReadyForNewChallenges">controlPlaneReadyForNewChallenges</param>
        /// <param name="controlPlaneReadyForSettlement">controlPlaneReadyForSettlement</param>
        /// <param name="rails">rails</param>
        /// <param name="externalOnboarding">externalOnboarding</param>
        [JsonConstructor]
        internal PaymentReadiness(DateTimeOffset observedAt, string tenantStatus, bool tenantAcceptingNewChallenges, bool globalChallengesEnabled, bool globalSettlementEnabled, bool controlPlaneReadyForNewChallenges, bool controlPlaneReadyForSettlement, List<PaymentReadinessRail> rails, Object? externalOnboarding = default)
        {
            ObservedAt = observedAt;
            TenantStatus = tenantStatus;
            TenantAcceptingNewChallenges = tenantAcceptingNewChallenges;
            GlobalChallengesEnabled = globalChallengesEnabled;
            GlobalSettlementEnabled = globalSettlementEnabled;
            ControlPlaneReadyForNewChallenges = controlPlaneReadyForNewChallenges;
            ControlPlaneReadyForSettlement = controlPlaneReadyForSettlement;
            Rails = rails;
            ExternalOnboarding = externalOnboarding;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets ObservedAt
        /// </summary>
        [JsonPropertyName("observed_at")]
        public DateTimeOffset ObservedAt { get; }

        /// <summary>
        /// Gets or Sets TenantStatus
        /// </summary>
        [JsonPropertyName("tenant_status")]
        public string TenantStatus { get; }

        /// <summary>
        /// Gets or Sets TenantAcceptingNewChallenges
        /// </summary>
        [JsonPropertyName("tenant_accepting_new_challenges")]
        public bool TenantAcceptingNewChallenges { get; }

        /// <summary>
        /// Gets or Sets GlobalChallengesEnabled
        /// </summary>
        [JsonPropertyName("global_challenges_enabled")]
        public bool GlobalChallengesEnabled { get; }

        /// <summary>
        /// Gets or Sets GlobalSettlementEnabled
        /// </summary>
        [JsonPropertyName("global_settlement_enabled")]
        public bool GlobalSettlementEnabled { get; }

        /// <summary>
        /// Gets or Sets ControlPlaneReadyForNewChallenges
        /// </summary>
        [JsonPropertyName("control_plane_ready_for_new_challenges")]
        public bool ControlPlaneReadyForNewChallenges { get; }

        /// <summary>
        /// Gets or Sets ControlPlaneReadyForSettlement
        /// </summary>
        [JsonPropertyName("control_plane_ready_for_settlement")]
        public bool ControlPlaneReadyForSettlement { get; }

        /// <summary>
        /// Gets or Sets Rails
        /// </summary>
        [JsonPropertyName("rails")]
        public List<PaymentReadinessRail> Rails { get; }

        /// <summary>
        /// Gets or Sets ExternalOnboarding
        /// </summary>
        [JsonPropertyName("external_onboarding")]
        public Object? ExternalOnboarding { get; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PaymentReadiness {\n");
            sb.Append("  ObservedAt: ").Append(ObservedAt).Append("\n");
            sb.Append("  TenantStatus: ").Append(TenantStatus).Append("\n");
            sb.Append("  TenantAcceptingNewChallenges: ").Append(TenantAcceptingNewChallenges).Append("\n");
            sb.Append("  GlobalChallengesEnabled: ").Append(GlobalChallengesEnabled).Append("\n");
            sb.Append("  GlobalSettlementEnabled: ").Append(GlobalSettlementEnabled).Append("\n");
            sb.Append("  ControlPlaneReadyForNewChallenges: ").Append(ControlPlaneReadyForNewChallenges).Append("\n");
            sb.Append("  ControlPlaneReadyForSettlement: ").Append(ControlPlaneReadyForSettlement).Append("\n");
            sb.Append("  Rails: ").Append(Rails).Append("\n");
            sb.Append("  ExternalOnboarding: ").Append(ExternalOnboarding).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PaymentReadiness" />
    /// </summary>
    public partial class PaymentReadinessJsonConverter : JsonConverter<PaymentReadiness>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentReadinessJsonConverter" /> class.
        /// </summary>
        public PaymentReadinessJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize ObservedAt
        /// </summary>
        public string ObservedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="PaymentReadiness" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PaymentReadiness Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<DateTimeOffset?> observedAt = default;
            Option<string?> tenantStatus = default;
            Option<bool?> tenantAcceptingNewChallenges = default;
            Option<bool?> globalChallengesEnabled = default;
            Option<bool?> globalSettlementEnabled = default;
            Option<bool?> controlPlaneReadyForNewChallenges = default;
            Option<bool?> controlPlaneReadyForSettlement = default;
            Option<List<PaymentReadinessRail>?> rails = default;
            Option<Object?> externalOnboarding = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "observed_at":
                            observedAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "tenant_status":
                            tenantStatus = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "tenant_accepting_new_challenges":
                            tenantAcceptingNewChallenges = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "global_challenges_enabled":
                            globalChallengesEnabled = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "global_settlement_enabled":
                            globalSettlementEnabled = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "control_plane_ready_for_new_challenges":
                            controlPlaneReadyForNewChallenges = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "control_plane_ready_for_settlement":
                            controlPlaneReadyForSettlement = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "rails":
                            rails = new Option<List<PaymentReadinessRail>?>(JsonSerializer.Deserialize<List<PaymentReadinessRail>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "external_onboarding":
                            externalOnboarding = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!observedAt.IsSet)
                throw new ArgumentException("Property is required for class PaymentReadiness.", nameof(observedAt));

            if (!tenantStatus.IsSet)
                throw new ArgumentException("Property is required for class PaymentReadiness.", nameof(tenantStatus));

            if (!tenantAcceptingNewChallenges.IsSet)
                throw new ArgumentException("Property is required for class PaymentReadiness.", nameof(tenantAcceptingNewChallenges));

            if (!globalChallengesEnabled.IsSet)
                throw new ArgumentException("Property is required for class PaymentReadiness.", nameof(globalChallengesEnabled));

            if (!globalSettlementEnabled.IsSet)
                throw new ArgumentException("Property is required for class PaymentReadiness.", nameof(globalSettlementEnabled));

            if (!controlPlaneReadyForNewChallenges.IsSet)
                throw new ArgumentException("Property is required for class PaymentReadiness.", nameof(controlPlaneReadyForNewChallenges));

            if (!controlPlaneReadyForSettlement.IsSet)
                throw new ArgumentException("Property is required for class PaymentReadiness.", nameof(controlPlaneReadyForSettlement));

            if (!rails.IsSet)
                throw new ArgumentException("Property is required for class PaymentReadiness.", nameof(rails));

            if (!externalOnboarding.IsSet)
                throw new ArgumentException("Property is required for class PaymentReadiness.", nameof(externalOnboarding));

            if (observedAt.IsSet && observedAt.Value == null)
                throw new ArgumentNullException(nameof(observedAt), "Property is not nullable for class PaymentReadiness.");

            if (tenantStatus.IsSet && tenantStatus.Value == null)
                throw new ArgumentNullException(nameof(tenantStatus), "Property is not nullable for class PaymentReadiness.");

            if (tenantAcceptingNewChallenges.IsSet && tenantAcceptingNewChallenges.Value == null)
                throw new ArgumentNullException(nameof(tenantAcceptingNewChallenges), "Property is not nullable for class PaymentReadiness.");

            if (globalChallengesEnabled.IsSet && globalChallengesEnabled.Value == null)
                throw new ArgumentNullException(nameof(globalChallengesEnabled), "Property is not nullable for class PaymentReadiness.");

            if (globalSettlementEnabled.IsSet && globalSettlementEnabled.Value == null)
                throw new ArgumentNullException(nameof(globalSettlementEnabled), "Property is not nullable for class PaymentReadiness.");

            if (controlPlaneReadyForNewChallenges.IsSet && controlPlaneReadyForNewChallenges.Value == null)
                throw new ArgumentNullException(nameof(controlPlaneReadyForNewChallenges), "Property is not nullable for class PaymentReadiness.");

            if (controlPlaneReadyForSettlement.IsSet && controlPlaneReadyForSettlement.Value == null)
                throw new ArgumentNullException(nameof(controlPlaneReadyForSettlement), "Property is not nullable for class PaymentReadiness.");

            if (rails.IsSet && rails.Value == null)
                throw new ArgumentNullException(nameof(rails), "Property is not nullable for class PaymentReadiness.");

            return new PaymentReadiness(observedAt.Value!.Value!, tenantStatus.Value!, tenantAcceptingNewChallenges.Value!.Value!, globalChallengesEnabled.Value!.Value!, globalSettlementEnabled.Value!.Value!, controlPlaneReadyForNewChallenges.Value!.Value!, controlPlaneReadyForSettlement.Value!.Value!, rails.Value!, externalOnboarding.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="PaymentReadiness" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="paymentReadiness"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PaymentReadiness paymentReadiness, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, paymentReadiness, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PaymentReadiness" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="paymentReadiness"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PaymentReadiness paymentReadiness, JsonSerializerOptions jsonSerializerOptions)
        {
            if (paymentReadiness.TenantStatus == null)
                throw new ArgumentNullException(nameof(paymentReadiness.TenantStatus), "Property is required for class PaymentReadiness.");

            if (paymentReadiness.Rails == null)
                throw new ArgumentNullException(nameof(paymentReadiness.Rails), "Property is required for class PaymentReadiness.");

            writer.WriteString("observed_at", paymentReadiness.ObservedAt.ToString(ObservedAtFormat));

            writer.WriteString("tenant_status", paymentReadiness.TenantStatus);

            writer.WriteBoolean("tenant_accepting_new_challenges", paymentReadiness.TenantAcceptingNewChallenges);

            writer.WriteBoolean("global_challenges_enabled", paymentReadiness.GlobalChallengesEnabled);

            writer.WriteBoolean("global_settlement_enabled", paymentReadiness.GlobalSettlementEnabled);

            writer.WriteBoolean("control_plane_ready_for_new_challenges", paymentReadiness.ControlPlaneReadyForNewChallenges);

            writer.WriteBoolean("control_plane_ready_for_settlement", paymentReadiness.ControlPlaneReadyForSettlement);

            writer.WritePropertyName("rails");
            JsonSerializer.Serialize(writer, paymentReadiness.Rails, jsonSerializerOptions);
            if (paymentReadiness.ExternalOnboarding != null)
            {
                writer.WritePropertyName("external_onboarding");
                JsonSerializer.Serialize(writer, paymentReadiness.ExternalOnboarding, jsonSerializerOptions);
            }
            else
                writer.WriteNull("external_onboarding");
        }
    }

    /// <summary>
    /// The PaymentReadinessSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(PaymentReadiness))]
    public partial class PaymentReadinessSerializationContext : JsonSerializerContext { }
}
