// <auto-generated>
/*
 * x402api Public API
 *
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 1.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using X402Api.Client;

namespace X402Api.Model
{
    /// <summary>
    /// PaymentReceiptStatus
    /// </summary>
    public partial class PaymentReceiptStatus : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentReceiptStatus" /> class.
        /// </summary>
        /// <param name="paymentId">paymentId</param>
        /// <param name="state">state</param>
        /// <param name="confirmed">confirmed</param>
        /// <param name="finalized">finalized</param>
        /// <param name="transaction">transaction</param>
        /// <param name="network">network</param>
        /// <param name="receiptStatus">receiptStatus</param>
        /// <param name="confirmedAt">confirmedAt</param>
        /// <param name="finalizedAt">finalizedAt</param>
        [JsonConstructor]
        public PaymentReceiptStatus(Guid paymentId, string state, bool confirmed, bool finalized, string transaction, string network, ReceiptStatusEnum receiptStatus, DateTimeOffset? confirmedAt = default, DateTimeOffset? finalizedAt = default)
        {
            PaymentId = paymentId;
            State = state;
            Confirmed = confirmed;
            Finalized = finalized;
            Transaction = transaction;
            Network = network;
            ReceiptStatus = receiptStatus;
            ConfirmedAt = confirmedAt;
            FinalizedAt = finalizedAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets ReceiptStatus
        /// </summary>
        [JsonPropertyName("receipt_status")]
        public ReceiptStatusEnum ReceiptStatus { get; set; }

        /// <summary>
        /// Gets or Sets PaymentId
        /// </summary>
        [JsonPropertyName("payment_id")]
        public Guid PaymentId { get; set; }

        /// <summary>
        /// Gets or Sets State
        /// </summary>
        [JsonPropertyName("state")]
        public string State { get; set; }

        /// <summary>
        /// Gets or Sets Confirmed
        /// </summary>
        [JsonPropertyName("confirmed")]
        public bool Confirmed { get; set; }

        /// <summary>
        /// Gets or Sets Finalized
        /// </summary>
        [JsonPropertyName("finalized")]
        public bool Finalized { get; set; }

        /// <summary>
        /// Gets or Sets Transaction
        /// </summary>
        [JsonPropertyName("transaction")]
        public string Transaction { get; set; }

        /// <summary>
        /// Gets or Sets Network
        /// </summary>
        [JsonPropertyName("network")]
        public string Network { get; set; }

        /// <summary>
        /// Gets or Sets ConfirmedAt
        /// </summary>
        [JsonPropertyName("confirmed_at")]
        public DateTimeOffset? ConfirmedAt { get; set; }

        /// <summary>
        /// Gets or Sets FinalizedAt
        /// </summary>
        [JsonPropertyName("finalized_at")]
        public DateTimeOffset? FinalizedAt { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PaymentReceiptStatus {\n");
            sb.Append("  PaymentId: ").Append(PaymentId).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  Confirmed: ").Append(Confirmed).Append("\n");
            sb.Append("  Finalized: ").Append(Finalized).Append("\n");
            sb.Append("  Transaction: ").Append(Transaction).Append("\n");
            sb.Append("  Network: ").Append(Network).Append("\n");
            sb.Append("  ReceiptStatus: ").Append(ReceiptStatus).Append("\n");
            sb.Append("  ConfirmedAt: ").Append(ConfirmedAt).Append("\n");
            sb.Append("  FinalizedAt: ").Append(FinalizedAt).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PaymentReceiptStatus" />
    /// </summary>
    public partial class PaymentReceiptStatusJsonConverter : JsonConverter<PaymentReceiptStatus>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentReceiptStatusJsonConverter" /> class.
        /// </summary>
        public PaymentReceiptStatusJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize ConfirmedAt
        /// </summary>
        public string ConfirmedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize FinalizedAt
        /// </summary>
        public string FinalizedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="PaymentReceiptStatus" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PaymentReceiptStatus Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> paymentId = default;
            Option<string?> state = default;
            Option<bool?> confirmed = default;
            Option<bool?> finalized = default;
            Option<string?> transaction = default;
            Option<string?> network = default;
            Option<ReceiptStatusEnum?> receiptStatus = default;
            Option<DateTimeOffset?> confirmedAt = default;
            Option<DateTimeOffset?> finalizedAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "payment_id":
                            paymentId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "state":
                            state = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "confirmed":
                            confirmed = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "finalized":
                            finalized = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "transaction":
                            transaction = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "network":
                            network = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "receipt_status":
                            receiptStatus = new Option<ReceiptStatusEnum?>(JsonSerializer.Deserialize<ReceiptStatusEnum?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "confirmed_at":
                            confirmedAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "finalized_at":
                            finalizedAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!paymentId.IsSet)
                throw new ArgumentException("Property is required for class PaymentReceiptStatus.", nameof(paymentId));

            if (!state.IsSet)
                throw new ArgumentException("Property is required for class PaymentReceiptStatus.", nameof(state));

            if (!confirmed.IsSet)
                throw new ArgumentException("Property is required for class PaymentReceiptStatus.", nameof(confirmed));

            if (!finalized.IsSet)
                throw new ArgumentException("Property is required for class PaymentReceiptStatus.", nameof(finalized));

            if (!transaction.IsSet)
                throw new ArgumentException("Property is required for class PaymentReceiptStatus.", nameof(transaction));

            if (!network.IsSet)
                throw new ArgumentException("Property is required for class PaymentReceiptStatus.", nameof(network));

            if (!receiptStatus.IsSet)
                throw new ArgumentException("Property is required for class PaymentReceiptStatus.", nameof(receiptStatus));

            if (!confirmedAt.IsSet)
                throw new ArgumentException("Property is required for class PaymentReceiptStatus.", nameof(confirmedAt));

            if (!finalizedAt.IsSet)
                throw new ArgumentException("Property is required for class PaymentReceiptStatus.", nameof(finalizedAt));

            if (paymentId.IsSet && paymentId.Value == null)
                throw new ArgumentNullException(nameof(paymentId), "Property is not nullable for class PaymentReceiptStatus.");

            if (state.IsSet && state.Value == null)
                throw new ArgumentNullException(nameof(state), "Property is not nullable for class PaymentReceiptStatus.");

            if (confirmed.IsSet && confirmed.Value == null)
                throw new ArgumentNullException(nameof(confirmed), "Property is not nullable for class PaymentReceiptStatus.");

            if (finalized.IsSet && finalized.Value == null)
                throw new ArgumentNullException(nameof(finalized), "Property is not nullable for class PaymentReceiptStatus.");

            if (transaction.IsSet && transaction.Value == null)
                throw new ArgumentNullException(nameof(transaction), "Property is not nullable for class PaymentReceiptStatus.");

            if (network.IsSet && network.Value == null)
                throw new ArgumentNullException(nameof(network), "Property is not nullable for class PaymentReceiptStatus.");

            if (receiptStatus.IsSet && receiptStatus.Value == null)
                throw new ArgumentNullException(nameof(receiptStatus), "Property is not nullable for class PaymentReceiptStatus.");

            return new PaymentReceiptStatus(paymentId.Value!.Value!, state.Value!, confirmed.Value!.Value!, finalized.Value!.Value!, transaction.Value!, network.Value!, receiptStatus.Value!.Value!, confirmedAt.Value!, finalizedAt.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="PaymentReceiptStatus" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="paymentReceiptStatus"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PaymentReceiptStatus paymentReceiptStatus, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, paymentReceiptStatus, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PaymentReceiptStatus" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="paymentReceiptStatus"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PaymentReceiptStatus paymentReceiptStatus, JsonSerializerOptions jsonSerializerOptions)
        {
            if (paymentReceiptStatus.State == null)
                throw new ArgumentNullException(nameof(paymentReceiptStatus.State), "Property is required for class PaymentReceiptStatus.");

            if (paymentReceiptStatus.Transaction == null)
                throw new ArgumentNullException(nameof(paymentReceiptStatus.Transaction), "Property is required for class PaymentReceiptStatus.");

            if (paymentReceiptStatus.Network == null)
                throw new ArgumentNullException(nameof(paymentReceiptStatus.Network), "Property is required for class PaymentReceiptStatus.");

            writer.WriteString("payment_id", paymentReceiptStatus.PaymentId);

            writer.WriteString("state", paymentReceiptStatus.State);

            writer.WriteBoolean("confirmed", paymentReceiptStatus.Confirmed);

            writer.WriteBoolean("finalized", paymentReceiptStatus.Finalized);

            writer.WriteString("transaction", paymentReceiptStatus.Transaction);

            writer.WriteString("network", paymentReceiptStatus.Network);

            var receiptStatusRawValue = ReceiptStatusEnumValueConverter.ToJsonValue(paymentReceiptStatus.ReceiptStatus);
            writer.WriteString("receipt_status", receiptStatusRawValue);

            if (paymentReceiptStatus.ConfirmedAt != null)
                writer.WriteString("confirmed_at", paymentReceiptStatus.ConfirmedAt.Value.ToString(ConfirmedAtFormat));
            else
                writer.WriteNull("confirmed_at");

            if (paymentReceiptStatus.FinalizedAt != null)
                writer.WriteString("finalized_at", paymentReceiptStatus.FinalizedAt.Value.ToString(FinalizedAtFormat));
            else
                writer.WriteNull("finalized_at");
        }
    }

    /// <summary>
    /// The PaymentReceiptStatusSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(PaymentReceiptStatus))]
    public partial class PaymentReceiptStatusSerializationContext : JsonSerializerContext { }
}
