// <auto-generated>
/*
 * x402api Public API
 *
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using X402Api.Client;

namespace X402Api.Model
{
    /// <summary>
    /// PaymentReadinessAsset
    /// </summary>
    public partial class PaymentReadinessAsset : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentReadinessAsset" /> class.
        /// </summary>
        /// <param name="assetId">assetId</param>
        /// <param name="displayName">displayName</param>
        /// <param name="contractAddress">contractAddress</param>
        /// <param name="issuerNative">issuerNative</param>
        /// <param name="registryEnabled">registryEnabled</param>
        /// <param name="tenantEnabled">tenantEnabled</param>
        /// <param name="operatorAssistanceEnabled">operatorAssistanceEnabled</param>
        /// <param name="baseReadinessBlockers">baseReadinessBlockers</param>
        /// <param name="challengeControlReady">challengeControlReady</param>
        /// <param name="settlementControlReady">settlementControlReady</param>
        [JsonConstructor]
        internal PaymentReadinessAsset(string assetId, string displayName, string contractAddress, bool issuerNative, bool registryEnabled, bool tenantEnabled, bool operatorAssistanceEnabled, List<string> baseReadinessBlockers, bool challengeControlReady, bool settlementControlReady)
        {
            AssetId = assetId;
            DisplayName = displayName;
            ContractAddress = contractAddress;
            IssuerNative = issuerNative;
            RegistryEnabled = registryEnabled;
            TenantEnabled = tenantEnabled;
            OperatorAssistanceEnabled = operatorAssistanceEnabled;
            BaseReadinessBlockers = baseReadinessBlockers;
            ChallengeControlReady = challengeControlReady;
            SettlementControlReady = settlementControlReady;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets AssetId
        /// </summary>
        [JsonPropertyName("asset_id")]
        public string AssetId { get; }

        /// <summary>
        /// Gets or Sets DisplayName
        /// </summary>
        [JsonPropertyName("display_name")]
        public string DisplayName { get; }

        /// <summary>
        /// Gets or Sets ContractAddress
        /// </summary>
        [JsonPropertyName("contract_address")]
        public string ContractAddress { get; }

        /// <summary>
        /// Gets or Sets IssuerNative
        /// </summary>
        [JsonPropertyName("issuer_native")]
        public bool IssuerNative { get; }

        /// <summary>
        /// Gets or Sets RegistryEnabled
        /// </summary>
        [JsonPropertyName("registry_enabled")]
        public bool RegistryEnabled { get; }

        /// <summary>
        /// Gets or Sets TenantEnabled
        /// </summary>
        [JsonPropertyName("tenant_enabled")]
        public bool TenantEnabled { get; }

        /// <summary>
        /// Gets or Sets OperatorAssistanceEnabled
        /// </summary>
        [JsonPropertyName("operator_assistance_enabled")]
        public bool OperatorAssistanceEnabled { get; }

        /// <summary>
        /// Gets or Sets BaseReadinessBlockers
        /// </summary>
        [JsonPropertyName("base_readiness_blockers")]
        public List<string> BaseReadinessBlockers { get; }

        /// <summary>
        /// Gets or Sets ChallengeControlReady
        /// </summary>
        [JsonPropertyName("challenge_control_ready")]
        public bool ChallengeControlReady { get; }

        /// <summary>
        /// Gets or Sets SettlementControlReady
        /// </summary>
        [JsonPropertyName("settlement_control_ready")]
        public bool SettlementControlReady { get; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PaymentReadinessAsset {\n");
            sb.Append("  AssetId: ").Append(AssetId).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  ContractAddress: ").Append(ContractAddress).Append("\n");
            sb.Append("  IssuerNative: ").Append(IssuerNative).Append("\n");
            sb.Append("  RegistryEnabled: ").Append(RegistryEnabled).Append("\n");
            sb.Append("  TenantEnabled: ").Append(TenantEnabled).Append("\n");
            sb.Append("  OperatorAssistanceEnabled: ").Append(OperatorAssistanceEnabled).Append("\n");
            sb.Append("  BaseReadinessBlockers: ").Append(BaseReadinessBlockers).Append("\n");
            sb.Append("  ChallengeControlReady: ").Append(ChallengeControlReady).Append("\n");
            sb.Append("  SettlementControlReady: ").Append(SettlementControlReady).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PaymentReadinessAsset" />
    /// </summary>
    public partial class PaymentReadinessAssetJsonConverter : JsonConverter<PaymentReadinessAsset>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentReadinessAssetJsonConverter" /> class.
        /// </summary>
        public PaymentReadinessAssetJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="PaymentReadinessAsset" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PaymentReadinessAsset Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> assetId = default;
            Option<string?> displayName = default;
            Option<string?> contractAddress = default;
            Option<bool?> issuerNative = default;
            Option<bool?> registryEnabled = default;
            Option<bool?> tenantEnabled = default;
            Option<bool?> operatorAssistanceEnabled = default;
            Option<List<string>?> baseReadinessBlockers = default;
            Option<bool?> challengeControlReady = default;
            Option<bool?> settlementControlReady = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "asset_id":
                            assetId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "display_name":
                            displayName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "contract_address":
                            contractAddress = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "issuer_native":
                            issuerNative = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "registry_enabled":
                            registryEnabled = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "tenant_enabled":
                            tenantEnabled = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "operator_assistance_enabled":
                            operatorAssistanceEnabled = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "base_readiness_blockers":
                            baseReadinessBlockers = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "challenge_control_ready":
                            challengeControlReady = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "settlement_control_ready":
                            settlementControlReady = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!assetId.IsSet)
                throw new ArgumentException("Property is required for class PaymentReadinessAsset.", nameof(assetId));

            if (!displayName.IsSet)
                throw new ArgumentException("Property is required for class PaymentReadinessAsset.", nameof(displayName));

            if (!contractAddress.IsSet)
                throw new ArgumentException("Property is required for class PaymentReadinessAsset.", nameof(contractAddress));

            if (!issuerNative.IsSet)
                throw new ArgumentException("Property is required for class PaymentReadinessAsset.", nameof(issuerNative));

            if (!registryEnabled.IsSet)
                throw new ArgumentException("Property is required for class PaymentReadinessAsset.", nameof(registryEnabled));

            if (!tenantEnabled.IsSet)
                throw new ArgumentException("Property is required for class PaymentReadinessAsset.", nameof(tenantEnabled));

            if (!operatorAssistanceEnabled.IsSet)
                throw new ArgumentException("Property is required for class PaymentReadinessAsset.", nameof(operatorAssistanceEnabled));

            if (!baseReadinessBlockers.IsSet)
                throw new ArgumentException("Property is required for class PaymentReadinessAsset.", nameof(baseReadinessBlockers));

            if (!challengeControlReady.IsSet)
                throw new ArgumentException("Property is required for class PaymentReadinessAsset.", nameof(challengeControlReady));

            if (!settlementControlReady.IsSet)
                throw new ArgumentException("Property is required for class PaymentReadinessAsset.", nameof(settlementControlReady));

            if (assetId.IsSet && assetId.Value == null)
                throw new ArgumentNullException(nameof(assetId), "Property is not nullable for class PaymentReadinessAsset.");

            if (displayName.IsSet && displayName.Value == null)
                throw new ArgumentNullException(nameof(displayName), "Property is not nullable for class PaymentReadinessAsset.");

            if (contractAddress.IsSet && contractAddress.Value == null)
                throw new ArgumentNullException(nameof(contractAddress), "Property is not nullable for class PaymentReadinessAsset.");

            if (issuerNative.IsSet && issuerNative.Value == null)
                throw new ArgumentNullException(nameof(issuerNative), "Property is not nullable for class PaymentReadinessAsset.");

            if (registryEnabled.IsSet && registryEnabled.Value == null)
                throw new ArgumentNullException(nameof(registryEnabled), "Property is not nullable for class PaymentReadinessAsset.");

            if (tenantEnabled.IsSet && tenantEnabled.Value == null)
                throw new ArgumentNullException(nameof(tenantEnabled), "Property is not nullable for class PaymentReadinessAsset.");

            if (operatorAssistanceEnabled.IsSet && operatorAssistanceEnabled.Value == null)
                throw new ArgumentNullException(nameof(operatorAssistanceEnabled), "Property is not nullable for class PaymentReadinessAsset.");

            if (baseReadinessBlockers.IsSet && baseReadinessBlockers.Value == null)
                throw new ArgumentNullException(nameof(baseReadinessBlockers), "Property is not nullable for class PaymentReadinessAsset.");

            if (challengeControlReady.IsSet && challengeControlReady.Value == null)
                throw new ArgumentNullException(nameof(challengeControlReady), "Property is not nullable for class PaymentReadinessAsset.");

            if (settlementControlReady.IsSet && settlementControlReady.Value == null)
                throw new ArgumentNullException(nameof(settlementControlReady), "Property is not nullable for class PaymentReadinessAsset.");

            return new PaymentReadinessAsset(assetId.Value!, displayName.Value!, contractAddress.Value!, issuerNative.Value!.Value!, registryEnabled.Value!.Value!, tenantEnabled.Value!.Value!, operatorAssistanceEnabled.Value!.Value!, baseReadinessBlockers.Value!, challengeControlReady.Value!.Value!, settlementControlReady.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="PaymentReadinessAsset" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="paymentReadinessAsset"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PaymentReadinessAsset paymentReadinessAsset, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, paymentReadinessAsset, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PaymentReadinessAsset" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="paymentReadinessAsset"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PaymentReadinessAsset paymentReadinessAsset, JsonSerializerOptions jsonSerializerOptions)
        {
            if (paymentReadinessAsset.AssetId == null)
                throw new ArgumentNullException(nameof(paymentReadinessAsset.AssetId), "Property is required for class PaymentReadinessAsset.");

            if (paymentReadinessAsset.DisplayName == null)
                throw new ArgumentNullException(nameof(paymentReadinessAsset.DisplayName), "Property is required for class PaymentReadinessAsset.");

            if (paymentReadinessAsset.ContractAddress == null)
                throw new ArgumentNullException(nameof(paymentReadinessAsset.ContractAddress), "Property is required for class PaymentReadinessAsset.");

            if (paymentReadinessAsset.BaseReadinessBlockers == null)
                throw new ArgumentNullException(nameof(paymentReadinessAsset.BaseReadinessBlockers), "Property is required for class PaymentReadinessAsset.");

            writer.WriteString("asset_id", paymentReadinessAsset.AssetId);

            writer.WriteString("display_name", paymentReadinessAsset.DisplayName);

            writer.WriteString("contract_address", paymentReadinessAsset.ContractAddress);

            writer.WriteBoolean("issuer_native", paymentReadinessAsset.IssuerNative);

            writer.WriteBoolean("registry_enabled", paymentReadinessAsset.RegistryEnabled);

            writer.WriteBoolean("tenant_enabled", paymentReadinessAsset.TenantEnabled);

            writer.WriteBoolean("operator_assistance_enabled", paymentReadinessAsset.OperatorAssistanceEnabled);

            writer.WritePropertyName("base_readiness_blockers");
            JsonSerializer.Serialize(writer, paymentReadinessAsset.BaseReadinessBlockers, jsonSerializerOptions);
            writer.WriteBoolean("challenge_control_ready", paymentReadinessAsset.ChallengeControlReady);

            writer.WriteBoolean("settlement_control_ready", paymentReadinessAsset.SettlementControlReady);
        }
    }

    /// <summary>
    /// The PaymentReadinessAssetSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(PaymentReadinessAsset))]
    public partial class PaymentReadinessAssetSerializationContext : JsonSerializerContext { }
}
