// <auto-generated>
/*
 * x402api Public API
 *
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 1.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using X402Api.Client;

namespace X402Api.Model
{
    /// <summary>
    /// PublicFeePolicyDocument
    /// </summary>
    public partial class PublicFeePolicyDocument : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PublicFeePolicyDocument" /> class.
        /// </summary>
        /// <param name="type">type</param>
        /// <param name="varVersion">varVersion</param>
        /// <param name="feeMode">feeMode</param>
        /// <param name="quoteCurrency">quoteCurrency</param>
        [JsonConstructor]
        public PublicFeePolicyDocument(string type, int varVersion, FeePolicyModeInputEnum feeMode, FeePolicyQuoteCurrencyInputEnum quoteCurrency)
        {
            Type = type;
            VarVersion = varVersion;
            FeeMode = feeMode;
            QuoteCurrency = quoteCurrency;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets FeeMode
        /// </summary>
        [JsonPropertyName("feeMode")]
        public FeePolicyModeInputEnum FeeMode { get; set; }

        /// <summary>
        /// Gets or Sets QuoteCurrency
        /// </summary>
        [JsonPropertyName("quoteCurrency")]
        public FeePolicyQuoteCurrencyInputEnum QuoteCurrency { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets VarVersion
        /// </summary>
        [JsonPropertyName("version")]
        public int VarVersion { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PublicFeePolicyDocument {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  VarVersion: ").Append(VarVersion).Append("\n");
            sb.Append("  FeeMode: ").Append(FeeMode).Append("\n");
            sb.Append("  QuoteCurrency: ").Append(QuoteCurrency).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // VarVersion (int) minimum
            if (this.VarVersion < (int)1)
            {
                yield return new ValidationResult("Invalid value for VarVersion, must be a value greater than or equal to 1.", new [] { "VarVersion" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PublicFeePolicyDocument" />
    /// </summary>
    public partial class PublicFeePolicyDocumentJsonConverter : JsonConverter<PublicFeePolicyDocument>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="PublicFeePolicyDocumentJsonConverter" /> class.
        /// </summary>
        public PublicFeePolicyDocumentJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="PublicFeePolicyDocument" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PublicFeePolicyDocument Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> type = default;
            Option<int?> varVersion = default;
            Option<FeePolicyModeInputEnum?> feeMode = default;
            Option<FeePolicyQuoteCurrencyInputEnum?> quoteCurrency = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "type":
                            type = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "version":
                            varVersion = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "feeMode":
                            feeMode = new Option<FeePolicyModeInputEnum?>(JsonSerializer.Deserialize<FeePolicyModeInputEnum?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "quoteCurrency":
                            quoteCurrency = new Option<FeePolicyQuoteCurrencyInputEnum?>(JsonSerializer.Deserialize<FeePolicyQuoteCurrencyInputEnum?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class PublicFeePolicyDocument.", nameof(type));

            if (!varVersion.IsSet)
                throw new ArgumentException("Property is required for class PublicFeePolicyDocument.", nameof(varVersion));

            if (!feeMode.IsSet)
                throw new ArgumentException("Property is required for class PublicFeePolicyDocument.", nameof(feeMode));

            if (!quoteCurrency.IsSet)
                throw new ArgumentException("Property is required for class PublicFeePolicyDocument.", nameof(quoteCurrency));

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class PublicFeePolicyDocument.");

            if (varVersion.IsSet && varVersion.Value == null)
                throw new ArgumentNullException(nameof(varVersion), "Property is not nullable for class PublicFeePolicyDocument.");

            if (feeMode.IsSet && feeMode.Value == null)
                throw new ArgumentNullException(nameof(feeMode), "Property is not nullable for class PublicFeePolicyDocument.");

            if (quoteCurrency.IsSet && quoteCurrency.Value == null)
                throw new ArgumentNullException(nameof(quoteCurrency), "Property is not nullable for class PublicFeePolicyDocument.");

            return new PublicFeePolicyDocument(type.Value!, varVersion.Value!.Value!, feeMode.Value!.Value!, quoteCurrency.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="PublicFeePolicyDocument" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="publicFeePolicyDocument"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PublicFeePolicyDocument publicFeePolicyDocument, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, publicFeePolicyDocument, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PublicFeePolicyDocument" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="publicFeePolicyDocument"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PublicFeePolicyDocument publicFeePolicyDocument, JsonSerializerOptions jsonSerializerOptions)
        {
            if (publicFeePolicyDocument.Type == null)
                throw new ArgumentNullException(nameof(publicFeePolicyDocument.Type), "Property is required for class PublicFeePolicyDocument.");

            writer.WriteString("type", publicFeePolicyDocument.Type);

            writer.WriteNumber("version", publicFeePolicyDocument.VarVersion);

            var feeModeRawValue = FeePolicyModeInputEnumValueConverter.ToJsonValue(publicFeePolicyDocument.FeeMode);
            writer.WriteString("feeMode", feeModeRawValue);

            var quoteCurrencyRawValue = FeePolicyQuoteCurrencyInputEnumValueConverter.ToJsonValue(publicFeePolicyDocument.QuoteCurrency);
            writer.WriteString("quoteCurrency", quoteCurrencyRawValue);
        }
    }

    /// <summary>
    /// The PublicFeePolicyDocumentSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(PublicFeePolicyDocument))]
    public partial class PublicFeePolicyDocumentSerializationContext : JsonSerializerContext { }
}
