// <auto-generated>
/*
 * x402api Public API
 *
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 1.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using X402Api.Client;

namespace X402Api.Model
{
    /// <summary>
    /// * &#x60;webhook&#x60; - webhook * &#x60;static&#x60; - static * &#x60;entitlement&#x60; - entitlement
    /// </summary>
    /// <value>* &#x60;webhook&#x60; - webhook * &#x60;static&#x60; - static * &#x60;entitlement&#x60; - entitlement</value>
    public enum ResourceInputFulfillmentModeEnum
    {
        /// <summary>
        /// Enum Webhook for value: webhook
        /// </summary>
        Webhook = 1,

        /// <summary>
        /// Enum Static for value: static
        /// </summary>
        Static = 2,

        /// <summary>
        /// Enum Entitlement for value: entitlement
        /// </summary>
        Entitlement = 3
    }

    /// <summary>
    /// Converts <see cref="ResourceInputFulfillmentModeEnum"/> to and from the JSON value
    /// </summary>
    public static class ResourceInputFulfillmentModeEnumValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="ResourceInputFulfillmentModeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ResourceInputFulfillmentModeEnum FromString(string value)
        {
            if (value.Equals("webhook"))
                return ResourceInputFulfillmentModeEnum.Webhook;

            if (value.Equals("static"))
                return ResourceInputFulfillmentModeEnum.Static;

            if (value.Equals("entitlement"))
                return ResourceInputFulfillmentModeEnum.Entitlement;

            throw new NotImplementedException($"Could not convert value to type ResourceInputFulfillmentModeEnum: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="ResourceInputFulfillmentModeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ResourceInputFulfillmentModeEnum? FromStringOrDefault(string value)
        {
            if (value.Equals("webhook"))
                return ResourceInputFulfillmentModeEnum.Webhook;

            if (value.Equals("static"))
                return ResourceInputFulfillmentModeEnum.Static;

            if (value.Equals("entitlement"))
                return ResourceInputFulfillmentModeEnum.Entitlement;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ResourceInputFulfillmentModeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(ResourceInputFulfillmentModeEnum value)
        {
            if (value == ResourceInputFulfillmentModeEnum.Webhook)
                return "webhook";

            if (value == ResourceInputFulfillmentModeEnum.Static)
                return "static";

            if (value == ResourceInputFulfillmentModeEnum.Entitlement)
                return "entitlement";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ResourceInputFulfillmentModeEnum"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class ResourceInputFulfillmentModeEnumJsonConverter : JsonConverter<ResourceInputFulfillmentModeEnum>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override ResourceInputFulfillmentModeEnum Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            ResourceInputFulfillmentModeEnum? result = rawValue == null
                ? null
                : ResourceInputFulfillmentModeEnumValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the ResourceInputFulfillmentModeEnum to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="resourceInputFulfillmentModeEnum"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, ResourceInputFulfillmentModeEnum resourceInputFulfillmentModeEnum, JsonSerializerOptions options)
        {
            writer.WriteStringValue(ResourceInputFulfillmentModeEnumValueConverter.ToJsonValue(resourceInputFulfillmentModeEnum).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ResourceInputFulfillmentModeEnum"/>
    /// </summary>
    public class ResourceInputFulfillmentModeEnumNullableJsonConverter : JsonConverter<ResourceInputFulfillmentModeEnum?>
    {
        /// <summary>
        /// Returns a ResourceInputFulfillmentModeEnum from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override ResourceInputFulfillmentModeEnum? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            if (reader.TokenType == JsonTokenType.Null)
                return null;

            string? rawValue = reader.GetString();

            ResourceInputFulfillmentModeEnum? result = rawValue == null
                ? null
                : ResourceInputFulfillmentModeEnumValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the ResourceInputFulfillmentModeEnum to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="resourceInputFulfillmentModeEnum"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, ResourceInputFulfillmentModeEnum? resourceInputFulfillmentModeEnum, JsonSerializerOptions options)
        {
            if (resourceInputFulfillmentModeEnum.HasValue)
                writer.WriteStringValue(ResourceInputFulfillmentModeEnumValueConverter.ToJsonValue(resourceInputFulfillmentModeEnum.Value).ToString());
            else
                writer.WriteNullValue();
        }
    }


    /// <summary>
    /// The ResourceInputFulfillmentModeEnumSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(ResourceInputFulfillmentModeEnum))]
    public partial class ResourceInputFulfillmentModeEnumSerializationContext : JsonSerializerContext { }
}
