// <auto-generated>
/*
 * x402api Public API
 *
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using X402Api.Client;

namespace X402Api.Model
{
    /// <summary>
    /// ResourceVersion
    /// </summary>
    public partial class ResourceVersion : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceVersion" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="varVersion">varVersion</param>
        /// <param name="method">method</param>
        /// <param name="path">path</param>
        /// <param name="description">description</param>
        /// <param name="mimeType">mimeType</param>
        /// <param name="fulfillmentMode">fulfillmentMode</param>
        /// <param name="fulfillmentConfig">fulfillmentConfig</param>
        /// <param name="feeMode">feeMode</param>
        /// <param name="quoteCurrency">quoteCurrency</param>
        /// <param name="feeAllowanceCapQuoteMicros">feeAllowanceCapQuoteMicros</param>
        /// <param name="state">state</param>
        /// <param name="prices">prices</param>
        [JsonConstructor]
        public ResourceVersion(Guid id, int varVersion, string method, string path, string description, string mimeType, ResourceVersionFulfillmentModeEnum fulfillmentMode, ResourceVersionFulfillmentConfig fulfillmentConfig, ResourceFeeModeEnum feeMode, ResourceQuoteCurrencyEnum quoteCurrency, string feeAllowanceCapQuoteMicros, ResourceVersionStateEnum state, List<ResourcePrice> prices)
        {
            Id = id;
            VarVersion = varVersion;
            Method = method;
            Path = path;
            Description = description;
            MimeType = mimeType;
            FulfillmentMode = fulfillmentMode;
            FulfillmentConfig = fulfillmentConfig;
            FeeMode = feeMode;
            QuoteCurrency = quoteCurrency;
            FeeAllowanceCapQuoteMicros = feeAllowanceCapQuoteMicros;
            State = state;
            Prices = prices;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets FulfillmentMode
        /// </summary>
        [JsonPropertyName("fulfillment_mode")]
        public ResourceVersionFulfillmentModeEnum FulfillmentMode { get; }

        /// <summary>
        /// Gets or Sets FeeMode
        /// </summary>
        [JsonPropertyName("fee_mode")]
        public ResourceFeeModeEnum FeeMode { get; }

        /// <summary>
        /// Gets or Sets QuoteCurrency
        /// </summary>
        [JsonPropertyName("quote_currency")]
        public ResourceQuoteCurrencyEnum QuoteCurrency { get; }

        /// <summary>
        /// Gets or Sets State
        /// </summary>
        [JsonPropertyName("state")]
        public ResourceVersionStateEnum State { get; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; }

        /// <summary>
        /// Gets or Sets VarVersion
        /// </summary>
        [JsonPropertyName("version")]
        public int VarVersion { get; }

        /// <summary>
        /// Gets or Sets Method
        /// </summary>
        [JsonPropertyName("method")]
        public string Method { get; }

        /// <summary>
        /// Gets or Sets Path
        /// </summary>
        [JsonPropertyName("path")]
        public string Path { get; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [JsonPropertyName("description")]
        public string Description { get; }

        /// <summary>
        /// Gets or Sets MimeType
        /// </summary>
        [JsonPropertyName("mime_type")]
        public string MimeType { get; }

        /// <summary>
        /// Gets or Sets FulfillmentConfig
        /// </summary>
        [JsonPropertyName("fulfillment_config")]
        public ResourceVersionFulfillmentConfig FulfillmentConfig { get; set; }

        /// <summary>
        /// Gets or Sets FeeAllowanceCapQuoteMicros
        /// </summary>
        [JsonPropertyName("fee_allowance_cap_quote_micros")]
        public string FeeAllowanceCapQuoteMicros { get; }

        /// <summary>
        /// Gets or Sets Prices
        /// </summary>
        [JsonPropertyName("prices")]
        public List<ResourcePrice> Prices { get; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ResourceVersion {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  VarVersion: ").Append(VarVersion).Append("\n");
            sb.Append("  Method: ").Append(Method).Append("\n");
            sb.Append("  Path: ").Append(Path).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  MimeType: ").Append(MimeType).Append("\n");
            sb.Append("  FulfillmentMode: ").Append(FulfillmentMode).Append("\n");
            sb.Append("  FulfillmentConfig: ").Append(FulfillmentConfig).Append("\n");
            sb.Append("  FeeMode: ").Append(FeeMode).Append("\n");
            sb.Append("  QuoteCurrency: ").Append(QuoteCurrency).Append("\n");
            sb.Append("  FeeAllowanceCapQuoteMicros: ").Append(FeeAllowanceCapQuoteMicros).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  Prices: ").Append(Prices).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ResourceVersion" />
    /// </summary>
    public partial class ResourceVersionJsonConverter : JsonConverter<ResourceVersion>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceVersionJsonConverter" /> class.
        /// </summary>
        public ResourceVersionJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="ResourceVersion" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ResourceVersion Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<int?> varVersion = default;
            Option<string?> method = default;
            Option<string?> path = default;
            Option<string?> description = default;
            Option<string?> mimeType = default;
            Option<ResourceVersionFulfillmentModeEnum?> fulfillmentMode = default;
            Option<ResourceVersionFulfillmentConfig?> fulfillmentConfig = default;
            Option<ResourceFeeModeEnum?> feeMode = default;
            Option<ResourceQuoteCurrencyEnum?> quoteCurrency = default;
            Option<string?> feeAllowanceCapQuoteMicros = default;
            Option<ResourceVersionStateEnum?> state = default;
            Option<List<ResourcePrice>?> prices = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "version":
                            varVersion = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "method":
                            method = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "path":
                            path = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "mime_type":
                            mimeType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "fulfillment_mode":
                            fulfillmentMode = new Option<ResourceVersionFulfillmentModeEnum?>(JsonSerializer.Deserialize<ResourceVersionFulfillmentModeEnum?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "fulfillment_config":
                            fulfillmentConfig = new Option<ResourceVersionFulfillmentConfig?>(JsonSerializer.Deserialize<ResourceVersionFulfillmentConfig>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "fee_mode":
                            feeMode = new Option<ResourceFeeModeEnum?>(JsonSerializer.Deserialize<ResourceFeeModeEnum?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "quote_currency":
                            quoteCurrency = new Option<ResourceQuoteCurrencyEnum?>(JsonSerializer.Deserialize<ResourceQuoteCurrencyEnum?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "fee_allowance_cap_quote_micros":
                            feeAllowanceCapQuoteMicros = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "state":
                            state = new Option<ResourceVersionStateEnum?>(JsonSerializer.Deserialize<ResourceVersionStateEnum?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "prices":
                            prices = new Option<List<ResourcePrice>?>(JsonSerializer.Deserialize<List<ResourcePrice>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class ResourceVersion.", nameof(id));

            if (!varVersion.IsSet)
                throw new ArgumentException("Property is required for class ResourceVersion.", nameof(varVersion));

            if (!method.IsSet)
                throw new ArgumentException("Property is required for class ResourceVersion.", nameof(method));

            if (!path.IsSet)
                throw new ArgumentException("Property is required for class ResourceVersion.", nameof(path));

            if (!description.IsSet)
                throw new ArgumentException("Property is required for class ResourceVersion.", nameof(description));

            if (!mimeType.IsSet)
                throw new ArgumentException("Property is required for class ResourceVersion.", nameof(mimeType));

            if (!fulfillmentMode.IsSet)
                throw new ArgumentException("Property is required for class ResourceVersion.", nameof(fulfillmentMode));

            if (!fulfillmentConfig.IsSet)
                throw new ArgumentException("Property is required for class ResourceVersion.", nameof(fulfillmentConfig));

            if (!feeMode.IsSet)
                throw new ArgumentException("Property is required for class ResourceVersion.", nameof(feeMode));

            if (!quoteCurrency.IsSet)
                throw new ArgumentException("Property is required for class ResourceVersion.", nameof(quoteCurrency));

            if (!feeAllowanceCapQuoteMicros.IsSet)
                throw new ArgumentException("Property is required for class ResourceVersion.", nameof(feeAllowanceCapQuoteMicros));

            if (!state.IsSet)
                throw new ArgumentException("Property is required for class ResourceVersion.", nameof(state));

            if (!prices.IsSet)
                throw new ArgumentException("Property is required for class ResourceVersion.", nameof(prices));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class ResourceVersion.");

            if (varVersion.IsSet && varVersion.Value == null)
                throw new ArgumentNullException(nameof(varVersion), "Property is not nullable for class ResourceVersion.");

            if (method.IsSet && method.Value == null)
                throw new ArgumentNullException(nameof(method), "Property is not nullable for class ResourceVersion.");

            if (path.IsSet && path.Value == null)
                throw new ArgumentNullException(nameof(path), "Property is not nullable for class ResourceVersion.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class ResourceVersion.");

            if (mimeType.IsSet && mimeType.Value == null)
                throw new ArgumentNullException(nameof(mimeType), "Property is not nullable for class ResourceVersion.");

            if (fulfillmentMode.IsSet && fulfillmentMode.Value == null)
                throw new ArgumentNullException(nameof(fulfillmentMode), "Property is not nullable for class ResourceVersion.");

            if (fulfillmentConfig.IsSet && fulfillmentConfig.Value == null)
                throw new ArgumentNullException(nameof(fulfillmentConfig), "Property is not nullable for class ResourceVersion.");

            if (feeMode.IsSet && feeMode.Value == null)
                throw new ArgumentNullException(nameof(feeMode), "Property is not nullable for class ResourceVersion.");

            if (quoteCurrency.IsSet && quoteCurrency.Value == null)
                throw new ArgumentNullException(nameof(quoteCurrency), "Property is not nullable for class ResourceVersion.");

            if (feeAllowanceCapQuoteMicros.IsSet && feeAllowanceCapQuoteMicros.Value == null)
                throw new ArgumentNullException(nameof(feeAllowanceCapQuoteMicros), "Property is not nullable for class ResourceVersion.");

            if (state.IsSet && state.Value == null)
                throw new ArgumentNullException(nameof(state), "Property is not nullable for class ResourceVersion.");

            if (prices.IsSet && prices.Value == null)
                throw new ArgumentNullException(nameof(prices), "Property is not nullable for class ResourceVersion.");

            return new ResourceVersion(id.Value!.Value!, varVersion.Value!.Value!, method.Value!, path.Value!, description.Value!, mimeType.Value!, fulfillmentMode.Value!.Value!, fulfillmentConfig.Value!, feeMode.Value!.Value!, quoteCurrency.Value!.Value!, feeAllowanceCapQuoteMicros.Value!, state.Value!.Value!, prices.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ResourceVersion" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="resourceVersion"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ResourceVersion resourceVersion, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, resourceVersion, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ResourceVersion" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="resourceVersion"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ResourceVersion resourceVersion, JsonSerializerOptions jsonSerializerOptions)
        {
            if (resourceVersion.Method == null)
                throw new ArgumentNullException(nameof(resourceVersion.Method), "Property is required for class ResourceVersion.");

            if (resourceVersion.Path == null)
                throw new ArgumentNullException(nameof(resourceVersion.Path), "Property is required for class ResourceVersion.");

            if (resourceVersion.Description == null)
                throw new ArgumentNullException(nameof(resourceVersion.Description), "Property is required for class ResourceVersion.");

            if (resourceVersion.MimeType == null)
                throw new ArgumentNullException(nameof(resourceVersion.MimeType), "Property is required for class ResourceVersion.");

            if (resourceVersion.FulfillmentConfig == null)
                throw new ArgumentNullException(nameof(resourceVersion.FulfillmentConfig), "Property is required for class ResourceVersion.");

            if (resourceVersion.FeeAllowanceCapQuoteMicros == null)
                throw new ArgumentNullException(nameof(resourceVersion.FeeAllowanceCapQuoteMicros), "Property is required for class ResourceVersion.");

            if (resourceVersion.Prices == null)
                throw new ArgumentNullException(nameof(resourceVersion.Prices), "Property is required for class ResourceVersion.");

            writer.WriteString("id", resourceVersion.Id);

            writer.WriteNumber("version", resourceVersion.VarVersion);

            writer.WriteString("method", resourceVersion.Method);

            writer.WriteString("path", resourceVersion.Path);

            writer.WriteString("description", resourceVersion.Description);

            writer.WriteString("mime_type", resourceVersion.MimeType);

            var fulfillmentModeRawValue = ResourceVersionFulfillmentModeEnumValueConverter.ToJsonValue(resourceVersion.FulfillmentMode);
            writer.WriteString("fulfillment_mode", fulfillmentModeRawValue);

            writer.WritePropertyName("fulfillment_config");
            JsonSerializer.Serialize(writer, resourceVersion.FulfillmentConfig, jsonSerializerOptions);
            var feeModeRawValue = ResourceFeeModeEnumValueConverter.ToJsonValue(resourceVersion.FeeMode);
            writer.WriteString("fee_mode", feeModeRawValue);

            var quoteCurrencyRawValue = ResourceQuoteCurrencyEnumValueConverter.ToJsonValue(resourceVersion.QuoteCurrency);
            writer.WriteString("quote_currency", quoteCurrencyRawValue);

            writer.WriteString("fee_allowance_cap_quote_micros", resourceVersion.FeeAllowanceCapQuoteMicros);

            var stateRawValue = ResourceVersionStateEnumValueConverter.ToJsonValue(resourceVersion.State);
            writer.WriteString("state", stateRawValue);

            writer.WritePropertyName("prices");
            JsonSerializer.Serialize(writer, resourceVersion.Prices, jsonSerializerOptions);
        }
    }

    /// <summary>
    /// The ResourceVersionSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(ResourceVersion))]
    public partial class ResourceVersionSerializationContext : JsonSerializerContext { }
}
