// <auto-generated>
/*
 * x402api Public API
 *
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using X402Api.Client;

namespace X402Api.Model
{
    /// <summary>
    /// * &#x60;created&#x60; - Created * &#x60;verifying&#x60; - Verifying * &#x60;verified&#x60; - Verified * &#x60;reserved&#x60; - Reserved * &#x60;broadcasting&#x60; - Broadcasting * &#x60;broadcast_unknown&#x60; - Broadcast unknown * &#x60;broadcast&#x60; - Broadcast * &#x60;confirming&#x60; - Confirming * &#x60;confirmed&#x60; - Confirmed * &#x60;finalized&#x60; - Finalized * &#x60;rejected&#x60; - Rejected * &#x60;failed&#x60; - Failed * &#x60;expired&#x60; - Expired * &#x60;reverted&#x60; - Reverted * &#x60;reorged&#x60; - Reorged * &#x60;late_confirmed&#x60; - Late confirmed * &#x60;manual_review&#x60; - Manual review
    /// </summary>
    /// <value>* &#x60;created&#x60; - Created * &#x60;verifying&#x60; - Verifying * &#x60;verified&#x60; - Verified * &#x60;reserved&#x60; - Reserved * &#x60;broadcasting&#x60; - Broadcasting * &#x60;broadcast_unknown&#x60; - Broadcast unknown * &#x60;broadcast&#x60; - Broadcast * &#x60;confirming&#x60; - Confirming * &#x60;confirmed&#x60; - Confirmed * &#x60;finalized&#x60; - Finalized * &#x60;rejected&#x60; - Rejected * &#x60;failed&#x60; - Failed * &#x60;expired&#x60; - Expired * &#x60;reverted&#x60; - Reverted * &#x60;reorged&#x60; - Reorged * &#x60;late_confirmed&#x60; - Late confirmed * &#x60;manual_review&#x60; - Manual review</value>
    public enum SettlementJobStateEnum
    {
        /// <summary>
        /// Enum Created for value: created
        /// </summary>
        Created = 1,

        /// <summary>
        /// Enum Verifying for value: verifying
        /// </summary>
        Verifying = 2,

        /// <summary>
        /// Enum Verified for value: verified
        /// </summary>
        Verified = 3,

        /// <summary>
        /// Enum Reserved for value: reserved
        /// </summary>
        Reserved = 4,

        /// <summary>
        /// Enum Broadcasting for value: broadcasting
        /// </summary>
        Broadcasting = 5,

        /// <summary>
        /// Enum BroadcastUnknown for value: broadcast_unknown
        /// </summary>
        BroadcastUnknown = 6,

        /// <summary>
        /// Enum Broadcast for value: broadcast
        /// </summary>
        Broadcast = 7,

        /// <summary>
        /// Enum Confirming for value: confirming
        /// </summary>
        Confirming = 8,

        /// <summary>
        /// Enum Confirmed for value: confirmed
        /// </summary>
        Confirmed = 9,

        /// <summary>
        /// Enum Finalized for value: finalized
        /// </summary>
        Finalized = 10,

        /// <summary>
        /// Enum Rejected for value: rejected
        /// </summary>
        Rejected = 11,

        /// <summary>
        /// Enum Failed for value: failed
        /// </summary>
        Failed = 12,

        /// <summary>
        /// Enum Expired for value: expired
        /// </summary>
        Expired = 13,

        /// <summary>
        /// Enum Reverted for value: reverted
        /// </summary>
        Reverted = 14,

        /// <summary>
        /// Enum Reorged for value: reorged
        /// </summary>
        Reorged = 15,

        /// <summary>
        /// Enum LateConfirmed for value: late_confirmed
        /// </summary>
        LateConfirmed = 16,

        /// <summary>
        /// Enum ManualReview for value: manual_review
        /// </summary>
        ManualReview = 17
    }

    /// <summary>
    /// Converts <see cref="SettlementJobStateEnum"/> to and from the JSON value
    /// </summary>
    public static class SettlementJobStateEnumValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="SettlementJobStateEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SettlementJobStateEnum FromString(string value)
        {
            if (value.Equals("created"))
                return SettlementJobStateEnum.Created;

            if (value.Equals("verifying"))
                return SettlementJobStateEnum.Verifying;

            if (value.Equals("verified"))
                return SettlementJobStateEnum.Verified;

            if (value.Equals("reserved"))
                return SettlementJobStateEnum.Reserved;

            if (value.Equals("broadcasting"))
                return SettlementJobStateEnum.Broadcasting;

            if (value.Equals("broadcast_unknown"))
                return SettlementJobStateEnum.BroadcastUnknown;

            if (value.Equals("broadcast"))
                return SettlementJobStateEnum.Broadcast;

            if (value.Equals("confirming"))
                return SettlementJobStateEnum.Confirming;

            if (value.Equals("confirmed"))
                return SettlementJobStateEnum.Confirmed;

            if (value.Equals("finalized"))
                return SettlementJobStateEnum.Finalized;

            if (value.Equals("rejected"))
                return SettlementJobStateEnum.Rejected;

            if (value.Equals("failed"))
                return SettlementJobStateEnum.Failed;

            if (value.Equals("expired"))
                return SettlementJobStateEnum.Expired;

            if (value.Equals("reverted"))
                return SettlementJobStateEnum.Reverted;

            if (value.Equals("reorged"))
                return SettlementJobStateEnum.Reorged;

            if (value.Equals("late_confirmed"))
                return SettlementJobStateEnum.LateConfirmed;

            if (value.Equals("manual_review"))
                return SettlementJobStateEnum.ManualReview;

            throw new NotImplementedException($"Could not convert value to type SettlementJobStateEnum: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="SettlementJobStateEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static SettlementJobStateEnum? FromStringOrDefault(string value)
        {
            if (value.Equals("created"))
                return SettlementJobStateEnum.Created;

            if (value.Equals("verifying"))
                return SettlementJobStateEnum.Verifying;

            if (value.Equals("verified"))
                return SettlementJobStateEnum.Verified;

            if (value.Equals("reserved"))
                return SettlementJobStateEnum.Reserved;

            if (value.Equals("broadcasting"))
                return SettlementJobStateEnum.Broadcasting;

            if (value.Equals("broadcast_unknown"))
                return SettlementJobStateEnum.BroadcastUnknown;

            if (value.Equals("broadcast"))
                return SettlementJobStateEnum.Broadcast;

            if (value.Equals("confirming"))
                return SettlementJobStateEnum.Confirming;

            if (value.Equals("confirmed"))
                return SettlementJobStateEnum.Confirmed;

            if (value.Equals("finalized"))
                return SettlementJobStateEnum.Finalized;

            if (value.Equals("rejected"))
                return SettlementJobStateEnum.Rejected;

            if (value.Equals("failed"))
                return SettlementJobStateEnum.Failed;

            if (value.Equals("expired"))
                return SettlementJobStateEnum.Expired;

            if (value.Equals("reverted"))
                return SettlementJobStateEnum.Reverted;

            if (value.Equals("reorged"))
                return SettlementJobStateEnum.Reorged;

            if (value.Equals("late_confirmed"))
                return SettlementJobStateEnum.LateConfirmed;

            if (value.Equals("manual_review"))
                return SettlementJobStateEnum.ManualReview;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="SettlementJobStateEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(SettlementJobStateEnum value)
        {
            if (value == SettlementJobStateEnum.Created)
                return "created";

            if (value == SettlementJobStateEnum.Verifying)
                return "verifying";

            if (value == SettlementJobStateEnum.Verified)
                return "verified";

            if (value == SettlementJobStateEnum.Reserved)
                return "reserved";

            if (value == SettlementJobStateEnum.Broadcasting)
                return "broadcasting";

            if (value == SettlementJobStateEnum.BroadcastUnknown)
                return "broadcast_unknown";

            if (value == SettlementJobStateEnum.Broadcast)
                return "broadcast";

            if (value == SettlementJobStateEnum.Confirming)
                return "confirming";

            if (value == SettlementJobStateEnum.Confirmed)
                return "confirmed";

            if (value == SettlementJobStateEnum.Finalized)
                return "finalized";

            if (value == SettlementJobStateEnum.Rejected)
                return "rejected";

            if (value == SettlementJobStateEnum.Failed)
                return "failed";

            if (value == SettlementJobStateEnum.Expired)
                return "expired";

            if (value == SettlementJobStateEnum.Reverted)
                return "reverted";

            if (value == SettlementJobStateEnum.Reorged)
                return "reorged";

            if (value == SettlementJobStateEnum.LateConfirmed)
                return "late_confirmed";

            if (value == SettlementJobStateEnum.ManualReview)
                return "manual_review";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SettlementJobStateEnum"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class SettlementJobStateEnumJsonConverter : JsonConverter<SettlementJobStateEnum>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override SettlementJobStateEnum Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            SettlementJobStateEnum? result = rawValue == null
                ? null
                : SettlementJobStateEnumValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the SettlementJobStateEnum to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="settlementJobStateEnum"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, SettlementJobStateEnum settlementJobStateEnum, JsonSerializerOptions options)
        {
            writer.WriteStringValue(SettlementJobStateEnumValueConverter.ToJsonValue(settlementJobStateEnum).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SettlementJobStateEnum"/>
    /// </summary>
    public class SettlementJobStateEnumNullableJsonConverter : JsonConverter<SettlementJobStateEnum?>
    {
        /// <summary>
        /// Returns a SettlementJobStateEnum from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override SettlementJobStateEnum? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            if (reader.TokenType == JsonTokenType.Null)
                return null;

            string? rawValue = reader.GetString();

            SettlementJobStateEnum? result = rawValue == null
                ? null
                : SettlementJobStateEnumValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the SettlementJobStateEnum to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="settlementJobStateEnum"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, SettlementJobStateEnum? settlementJobStateEnum, JsonSerializerOptions options)
        {
            if (settlementJobStateEnum.HasValue)
                writer.WriteStringValue(SettlementJobStateEnumValueConverter.ToJsonValue(settlementJobStateEnum.Value).ToString());
            else
                writer.WriteNullValue();
        }
    }


    /// <summary>
    /// The SettlementJobStateEnumSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(SettlementJobStateEnum))]
    public partial class SettlementJobStateEnumSerializationContext : JsonSerializerContext { }
}
