// <auto-generated>
/*
 * x402api Public API
 *
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 1.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using X402Api.Client;

namespace X402Api.Model
{
    /// <summary>
    /// * &#x60;not_created&#x60; - not_created * &#x60;created&#x60; - created
    /// </summary>
    /// <value>* &#x60;not_created&#x60; - not_created * &#x60;created&#x60; - created</value>
    public enum TenantPaymentFulfillmentProjectionStatusEnum
    {
        /// <summary>
        /// Enum NotCreated for value: not_created
        /// </summary>
        NotCreated = 1,

        /// <summary>
        /// Enum Created for value: created
        /// </summary>
        Created = 2
    }

    /// <summary>
    /// Converts <see cref="TenantPaymentFulfillmentProjectionStatusEnum"/> to and from the JSON value
    /// </summary>
    public static class TenantPaymentFulfillmentProjectionStatusEnumValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="TenantPaymentFulfillmentProjectionStatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TenantPaymentFulfillmentProjectionStatusEnum FromString(string value)
        {
            if (value.Equals("not_created"))
                return TenantPaymentFulfillmentProjectionStatusEnum.NotCreated;

            if (value.Equals("created"))
                return TenantPaymentFulfillmentProjectionStatusEnum.Created;

            throw new NotImplementedException($"Could not convert value to type TenantPaymentFulfillmentProjectionStatusEnum: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="TenantPaymentFulfillmentProjectionStatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TenantPaymentFulfillmentProjectionStatusEnum? FromStringOrDefault(string value)
        {
            if (value.Equals("not_created"))
                return TenantPaymentFulfillmentProjectionStatusEnum.NotCreated;

            if (value.Equals("created"))
                return TenantPaymentFulfillmentProjectionStatusEnum.Created;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TenantPaymentFulfillmentProjectionStatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(TenantPaymentFulfillmentProjectionStatusEnum value)
        {
            if (value == TenantPaymentFulfillmentProjectionStatusEnum.NotCreated)
                return "not_created";

            if (value == TenantPaymentFulfillmentProjectionStatusEnum.Created)
                return "created";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TenantPaymentFulfillmentProjectionStatusEnum"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class TenantPaymentFulfillmentProjectionStatusEnumJsonConverter : JsonConverter<TenantPaymentFulfillmentProjectionStatusEnum>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override TenantPaymentFulfillmentProjectionStatusEnum Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            TenantPaymentFulfillmentProjectionStatusEnum? result = rawValue == null
                ? null
                : TenantPaymentFulfillmentProjectionStatusEnumValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the TenantPaymentFulfillmentProjectionStatusEnum to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tenantPaymentFulfillmentProjectionStatusEnum"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, TenantPaymentFulfillmentProjectionStatusEnum tenantPaymentFulfillmentProjectionStatusEnum, JsonSerializerOptions options)
        {
            writer.WriteStringValue(TenantPaymentFulfillmentProjectionStatusEnumValueConverter.ToJsonValue(tenantPaymentFulfillmentProjectionStatusEnum).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TenantPaymentFulfillmentProjectionStatusEnum"/>
    /// </summary>
    public class TenantPaymentFulfillmentProjectionStatusEnumNullableJsonConverter : JsonConverter<TenantPaymentFulfillmentProjectionStatusEnum?>
    {
        /// <summary>
        /// Returns a TenantPaymentFulfillmentProjectionStatusEnum from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override TenantPaymentFulfillmentProjectionStatusEnum? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            if (reader.TokenType == JsonTokenType.Null)
                return null;

            string? rawValue = reader.GetString();

            TenantPaymentFulfillmentProjectionStatusEnum? result = rawValue == null
                ? null
                : TenantPaymentFulfillmentProjectionStatusEnumValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the TenantPaymentFulfillmentProjectionStatusEnum to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tenantPaymentFulfillmentProjectionStatusEnum"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, TenantPaymentFulfillmentProjectionStatusEnum? tenantPaymentFulfillmentProjectionStatusEnum, JsonSerializerOptions options)
        {
            if (tenantPaymentFulfillmentProjectionStatusEnum.HasValue)
                writer.WriteStringValue(TenantPaymentFulfillmentProjectionStatusEnumValueConverter.ToJsonValue(tenantPaymentFulfillmentProjectionStatusEnum.Value).ToString());
            else
                writer.WriteNullValue();
        }
    }


    /// <summary>
    /// The TenantPaymentFulfillmentProjectionStatusEnumSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(TenantPaymentFulfillmentProjectionStatusEnum))]
    public partial class TenantPaymentFulfillmentProjectionStatusEnumSerializationContext : JsonSerializerContext { }
}
