// <auto-generated>
/*
 * x402api Public API
 *
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using X402Api.Client;

namespace X402Api.Model
{
    /// <summary>
    /// TenantPaymentOrderProjection
    /// </summary>
    public partial class TenantPaymentOrderProjection : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TenantPaymentOrderProjection" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="status">status</param>
        /// <param name="buyerPaymentIdentifier">buyerPaymentIdentifier</param>
        /// <param name="paidAt">paidAt</param>
        /// <param name="fulfilledAt">fulfilledAt</param>
        [JsonConstructor]
        public TenantPaymentOrderProjection(Guid id, string status, string? buyerPaymentIdentifier = default, DateTimeOffset? paidAt = default, DateTimeOffset? fulfilledAt = default)
        {
            Id = id;
            Status = status;
            BuyerPaymentIdentifier = buyerPaymentIdentifier;
            PaidAt = paidAt;
            FulfilledAt = fulfilledAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets BuyerPaymentIdentifier
        /// </summary>
        [JsonPropertyName("buyer_payment_identifier")]
        public string? BuyerPaymentIdentifier { get; set; }

        /// <summary>
        /// Gets or Sets PaidAt
        /// </summary>
        [JsonPropertyName("paid_at")]
        public DateTimeOffset? PaidAt { get; set; }

        /// <summary>
        /// Gets or Sets FulfilledAt
        /// </summary>
        [JsonPropertyName("fulfilled_at")]
        public DateTimeOffset? FulfilledAt { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TenantPaymentOrderProjection {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  BuyerPaymentIdentifier: ").Append(BuyerPaymentIdentifier).Append("\n");
            sb.Append("  PaidAt: ").Append(PaidAt).Append("\n");
            sb.Append("  FulfilledAt: ").Append(FulfilledAt).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TenantPaymentOrderProjection" />
    /// </summary>
    public partial class TenantPaymentOrderProjectionJsonConverter : JsonConverter<TenantPaymentOrderProjection>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="TenantPaymentOrderProjectionJsonConverter" /> class.
        /// </summary>
        public TenantPaymentOrderProjectionJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize PaidAt
        /// </summary>
        public string PaidAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize FulfilledAt
        /// </summary>
        public string FulfilledAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="TenantPaymentOrderProjection" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TenantPaymentOrderProjection Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<string?> status = default;
            Option<string?> buyerPaymentIdentifier = default;
            Option<DateTimeOffset?> paidAt = default;
            Option<DateTimeOffset?> fulfilledAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "buyer_payment_identifier":
                            buyerPaymentIdentifier = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "paid_at":
                            paidAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "fulfilled_at":
                            fulfilledAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class TenantPaymentOrderProjection.", nameof(id));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class TenantPaymentOrderProjection.", nameof(status));

            if (!buyerPaymentIdentifier.IsSet)
                throw new ArgumentException("Property is required for class TenantPaymentOrderProjection.", nameof(buyerPaymentIdentifier));

            if (!paidAt.IsSet)
                throw new ArgumentException("Property is required for class TenantPaymentOrderProjection.", nameof(paidAt));

            if (!fulfilledAt.IsSet)
                throw new ArgumentException("Property is required for class TenantPaymentOrderProjection.", nameof(fulfilledAt));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class TenantPaymentOrderProjection.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class TenantPaymentOrderProjection.");

            return new TenantPaymentOrderProjection(id.Value!.Value!, status.Value!, buyerPaymentIdentifier.Value!, paidAt.Value!, fulfilledAt.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="TenantPaymentOrderProjection" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tenantPaymentOrderProjection"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TenantPaymentOrderProjection tenantPaymentOrderProjection, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, tenantPaymentOrderProjection, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TenantPaymentOrderProjection" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tenantPaymentOrderProjection"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, TenantPaymentOrderProjection tenantPaymentOrderProjection, JsonSerializerOptions jsonSerializerOptions)
        {
            if (tenantPaymentOrderProjection.Status == null)
                throw new ArgumentNullException(nameof(tenantPaymentOrderProjection.Status), "Property is required for class TenantPaymentOrderProjection.");

            writer.WriteString("id", tenantPaymentOrderProjection.Id);

            writer.WriteString("status", tenantPaymentOrderProjection.Status);

            if (tenantPaymentOrderProjection.BuyerPaymentIdentifier != null)
                writer.WriteString("buyer_payment_identifier", tenantPaymentOrderProjection.BuyerPaymentIdentifier);
            else
                writer.WriteNull("buyer_payment_identifier");

            if (tenantPaymentOrderProjection.PaidAt != null)
                writer.WriteString("paid_at", tenantPaymentOrderProjection.PaidAt.Value.ToString(PaidAtFormat));
            else
                writer.WriteNull("paid_at");

            if (tenantPaymentOrderProjection.FulfilledAt != null)
                writer.WriteString("fulfilled_at", tenantPaymentOrderProjection.FulfilledAt.Value.ToString(FulfilledAtFormat));
            else
                writer.WriteNull("fulfilled_at");
        }
    }

    /// <summary>
    /// The TenantPaymentOrderProjectionSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(TenantPaymentOrderProjection))]
    public partial class TenantPaymentOrderProjectionSerializationContext : JsonSerializerContext { }
}
