// <auto-generated>
/*
 * x402api Public API
 *
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 1.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using X402Api.Client;

namespace X402Api.Model
{
    /// <summary>
    /// TenantPaymentFulfillmentProjection
    /// </summary>
    public partial class TenantPaymentFulfillmentProjection : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TenantPaymentFulfillmentProjection" /> class.
        /// </summary>
        /// <param name="status">status</param>
        /// <param name="mode">mode</param>
        /// <param name="state">state</param>
        /// <param name="attemptCount">attemptCount</param>
        /// <param name="lastErrorCode">lastErrorCode</param>
        /// <param name="id">id</param>
        /// <param name="completedAt">completedAt</param>
        [JsonConstructor]
        public TenantPaymentFulfillmentProjection(TenantPaymentFulfillmentProjectionStatusEnum status, string mode, string state, int attemptCount, string lastErrorCode, Guid? id = default, DateTimeOffset? completedAt = default)
        {
            Status = status;
            Mode = mode;
            State = state;
            AttemptCount = attemptCount;
            LastErrorCode = lastErrorCode;
            Id = id;
            CompletedAt = completedAt;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public TenantPaymentFulfillmentProjectionStatusEnum Status { get; set; }

        /// <summary>
        /// Gets or Sets Mode
        /// </summary>
        [JsonPropertyName("mode")]
        public string Mode { get; set; }

        /// <summary>
        /// Gets or Sets State
        /// </summary>
        [JsonPropertyName("state")]
        public string State { get; set; }

        /// <summary>
        /// Gets or Sets AttemptCount
        /// </summary>
        [JsonPropertyName("attempt_count")]
        public int AttemptCount { get; set; }

        /// <summary>
        /// Gets or Sets LastErrorCode
        /// </summary>
        [JsonPropertyName("last_error_code")]
        public string LastErrorCode { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid? Id { get; set; }

        /// <summary>
        /// Gets or Sets CompletedAt
        /// </summary>
        [JsonPropertyName("completed_at")]
        public DateTimeOffset? CompletedAt { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TenantPaymentFulfillmentProjection {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Mode: ").Append(Mode).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  AttemptCount: ").Append(AttemptCount).Append("\n");
            sb.Append("  LastErrorCode: ").Append(LastErrorCode).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  CompletedAt: ").Append(CompletedAt).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // AttemptCount (int) minimum
            if (this.AttemptCount < (int)0)
            {
                yield return new ValidationResult("Invalid value for AttemptCount, must be a value greater than or equal to 0.", new [] { "AttemptCount" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TenantPaymentFulfillmentProjection" />
    /// </summary>
    public partial class TenantPaymentFulfillmentProjectionJsonConverter : JsonConverter<TenantPaymentFulfillmentProjection>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="TenantPaymentFulfillmentProjectionJsonConverter" /> class.
        /// </summary>
        public TenantPaymentFulfillmentProjectionJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize CompletedAt
        /// </summary>
        public string CompletedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="TenantPaymentFulfillmentProjection" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TenantPaymentFulfillmentProjection Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<TenantPaymentFulfillmentProjectionStatusEnum?> status = default;
            Option<string?> mode = default;
            Option<string?> state = default;
            Option<int?> attemptCount = default;
            Option<string?> lastErrorCode = default;
            Option<Guid?> id = default;
            Option<DateTimeOffset?> completedAt = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "status":
                            status = new Option<TenantPaymentFulfillmentProjectionStatusEnum?>(JsonSerializer.Deserialize<TenantPaymentFulfillmentProjectionStatusEnum?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "mode":
                            mode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "state":
                            state = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "attempt_count":
                            attemptCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "last_error_code":
                            lastErrorCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "completed_at":
                            completedAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class TenantPaymentFulfillmentProjection.", nameof(status));

            if (!mode.IsSet)
                throw new ArgumentException("Property is required for class TenantPaymentFulfillmentProjection.", nameof(mode));

            if (!state.IsSet)
                throw new ArgumentException("Property is required for class TenantPaymentFulfillmentProjection.", nameof(state));

            if (!attemptCount.IsSet)
                throw new ArgumentException("Property is required for class TenantPaymentFulfillmentProjection.", nameof(attemptCount));

            if (!lastErrorCode.IsSet)
                throw new ArgumentException("Property is required for class TenantPaymentFulfillmentProjection.", nameof(lastErrorCode));

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class TenantPaymentFulfillmentProjection.", nameof(id));

            if (!completedAt.IsSet)
                throw new ArgumentException("Property is required for class TenantPaymentFulfillmentProjection.", nameof(completedAt));

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class TenantPaymentFulfillmentProjection.");

            if (mode.IsSet && mode.Value == null)
                throw new ArgumentNullException(nameof(mode), "Property is not nullable for class TenantPaymentFulfillmentProjection.");

            if (state.IsSet && state.Value == null)
                throw new ArgumentNullException(nameof(state), "Property is not nullable for class TenantPaymentFulfillmentProjection.");

            if (attemptCount.IsSet && attemptCount.Value == null)
                throw new ArgumentNullException(nameof(attemptCount), "Property is not nullable for class TenantPaymentFulfillmentProjection.");

            if (lastErrorCode.IsSet && lastErrorCode.Value == null)
                throw new ArgumentNullException(nameof(lastErrorCode), "Property is not nullable for class TenantPaymentFulfillmentProjection.");

            return new TenantPaymentFulfillmentProjection(status.Value!.Value!, mode.Value!, state.Value!, attemptCount.Value!.Value!, lastErrorCode.Value!, id.Value!, completedAt.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="TenantPaymentFulfillmentProjection" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tenantPaymentFulfillmentProjection"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TenantPaymentFulfillmentProjection tenantPaymentFulfillmentProjection, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, tenantPaymentFulfillmentProjection, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TenantPaymentFulfillmentProjection" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tenantPaymentFulfillmentProjection"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, TenantPaymentFulfillmentProjection tenantPaymentFulfillmentProjection, JsonSerializerOptions jsonSerializerOptions)
        {
            if (tenantPaymentFulfillmentProjection.Mode == null)
                throw new ArgumentNullException(nameof(tenantPaymentFulfillmentProjection.Mode), "Property is required for class TenantPaymentFulfillmentProjection.");

            if (tenantPaymentFulfillmentProjection.State == null)
                throw new ArgumentNullException(nameof(tenantPaymentFulfillmentProjection.State), "Property is required for class TenantPaymentFulfillmentProjection.");

            if (tenantPaymentFulfillmentProjection.LastErrorCode == null)
                throw new ArgumentNullException(nameof(tenantPaymentFulfillmentProjection.LastErrorCode), "Property is required for class TenantPaymentFulfillmentProjection.");

            var statusRawValue = TenantPaymentFulfillmentProjectionStatusEnumValueConverter.ToJsonValue(tenantPaymentFulfillmentProjection.Status);
            writer.WriteString("status", statusRawValue);

            writer.WriteString("mode", tenantPaymentFulfillmentProjection.Mode);

            writer.WriteString("state", tenantPaymentFulfillmentProjection.State);

            writer.WriteNumber("attempt_count", tenantPaymentFulfillmentProjection.AttemptCount);

            writer.WriteString("last_error_code", tenantPaymentFulfillmentProjection.LastErrorCode);

            if (tenantPaymentFulfillmentProjection.Id != null)
                writer.WriteString("id", tenantPaymentFulfillmentProjection.Id.Value);
            else
                writer.WriteNull("id");

            if (tenantPaymentFulfillmentProjection.CompletedAt != null)
                writer.WriteString("completed_at", tenantPaymentFulfillmentProjection.CompletedAt.Value.ToString(CompletedAtFormat));
            else
                writer.WriteNull("completed_at");
        }
    }

    /// <summary>
    /// The TenantPaymentFulfillmentProjectionSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(TenantPaymentFulfillmentProjection))]
    public partial class TenantPaymentFulfillmentProjectionSerializationContext : JsonSerializerContext { }
}
