// <auto-generated>
/*
 * x402api Public API
 *
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 1.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using X402Api.Client;

namespace X402Api.Model
{
    /// <summary>
    /// * &#x60;pending&#x60; - pending * &#x60;active&#x60; - active * &#x60;draining&#x60; - draining * &#x60;revoked&#x60; - revoked
    /// </summary>
    /// <value>* &#x60;pending&#x60; - pending * &#x60;active&#x60; - active * &#x60;draining&#x60; - draining * &#x60;revoked&#x60; - revoked</value>
    public enum WalletVersionStateEnum
    {
        /// <summary>
        /// Enum Pending for value: pending
        /// </summary>
        Pending = 1,

        /// <summary>
        /// Enum Active for value: active
        /// </summary>
        Active = 2,

        /// <summary>
        /// Enum Draining for value: draining
        /// </summary>
        Draining = 3,

        /// <summary>
        /// Enum Revoked for value: revoked
        /// </summary>
        Revoked = 4
    }

    /// <summary>
    /// Converts <see cref="WalletVersionStateEnum"/> to and from the JSON value
    /// </summary>
    public static class WalletVersionStateEnumValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="WalletVersionStateEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static WalletVersionStateEnum FromString(string value)
        {
            if (value.Equals("pending"))
                return WalletVersionStateEnum.Pending;

            if (value.Equals("active"))
                return WalletVersionStateEnum.Active;

            if (value.Equals("draining"))
                return WalletVersionStateEnum.Draining;

            if (value.Equals("revoked"))
                return WalletVersionStateEnum.Revoked;

            throw new NotImplementedException($"Could not convert value to type WalletVersionStateEnum: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="WalletVersionStateEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static WalletVersionStateEnum? FromStringOrDefault(string value)
        {
            if (value.Equals("pending"))
                return WalletVersionStateEnum.Pending;

            if (value.Equals("active"))
                return WalletVersionStateEnum.Active;

            if (value.Equals("draining"))
                return WalletVersionStateEnum.Draining;

            if (value.Equals("revoked"))
                return WalletVersionStateEnum.Revoked;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="WalletVersionStateEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(WalletVersionStateEnum value)
        {
            if (value == WalletVersionStateEnum.Pending)
                return "pending";

            if (value == WalletVersionStateEnum.Active)
                return "active";

            if (value == WalletVersionStateEnum.Draining)
                return "draining";

            if (value == WalletVersionStateEnum.Revoked)
                return "revoked";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WalletVersionStateEnum"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class WalletVersionStateEnumJsonConverter : JsonConverter<WalletVersionStateEnum>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override WalletVersionStateEnum Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            WalletVersionStateEnum? result = rawValue == null
                ? null
                : WalletVersionStateEnumValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the WalletVersionStateEnum to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="walletVersionStateEnum"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, WalletVersionStateEnum walletVersionStateEnum, JsonSerializerOptions options)
        {
            writer.WriteStringValue(WalletVersionStateEnumValueConverter.ToJsonValue(walletVersionStateEnum).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WalletVersionStateEnum"/>
    /// </summary>
    public class WalletVersionStateEnumNullableJsonConverter : JsonConverter<WalletVersionStateEnum?>
    {
        /// <summary>
        /// Returns a WalletVersionStateEnum from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override WalletVersionStateEnum? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            if (reader.TokenType == JsonTokenType.Null)
                return null;

            string? rawValue = reader.GetString();

            WalletVersionStateEnum? result = rawValue == null
                ? null
                : WalletVersionStateEnumValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the WalletVersionStateEnum to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="walletVersionStateEnum"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, WalletVersionStateEnum? walletVersionStateEnum, JsonSerializerOptions options)
        {
            if (walletVersionStateEnum.HasValue)
                writer.WriteStringValue(WalletVersionStateEnumValueConverter.ToJsonValue(walletVersionStateEnum.Value).ToString());
            else
                writer.WriteNullValue();
        }
    }


    /// <summary>
    /// The WalletVersionStateEnumSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(WalletVersionStateEnum))]
    public partial class WalletVersionStateEnumSerializationContext : JsonSerializerContext { }
}
