// <auto-generated>
/*
 * x402api Public API
 *
 * Public External-Wallet x402 integration endpoints for programmatic charges, readiness, receiving addresses, resources, payments, receipts, and facilitator discovery.
 *
 * The version of the OpenAPI document: 1.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization.Metadata;
using X402Api.Client;

namespace X402Api.Model
{
    /// <summary>
    /// WalletFencedChainReseedContext
    /// </summary>
    public partial class WalletFencedChainReseedContext : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WalletFencedChainReseedContext" /> class.
        /// </summary>
        /// <param name="checkpointId">checkpointId</param>
        /// <param name="network">network</param>
        /// <param name="finality">finality</param>
        /// <param name="manifestDigest">manifestDigest</param>
        /// <param name="policyDigest">policyDigest</param>
        /// <param name="expectedGeneration">expectedGeneration</param>
        /// <param name="expectedNextBlockNumber">expectedNextBlockNumber</param>
        /// <param name="expectedLastScannedBlockHash">expectedLastScannedBlockHash</param>
        /// <param name="expectedReviewRequiredAt">expectedReviewRequiredAt</param>
        /// <param name="expectedReviewErrorCode">expectedReviewErrorCode</param>
        /// <param name="observedAt">observedAt</param>
        /// <param name="walletVersionId">walletVersionId</param>
        /// <param name="walletVersion">walletVersion</param>
        /// <param name="walletAddress">walletAddress</param>
        /// <param name="walletVersionState">walletVersionState</param>
        /// <param name="expectedLastScannedBlockNumber">expectedLastScannedBlockNumber</param>
        [JsonConstructor]
        public WalletFencedChainReseedContext(Guid checkpointId, string network, WalletObservationFinalityEnum finality, string manifestDigest, string policyDigest, int expectedGeneration, string expectedNextBlockNumber, string expectedLastScannedBlockHash, DateTimeOffset expectedReviewRequiredAt, string expectedReviewErrorCode, DateTimeOffset observedAt, Guid walletVersionId, int walletVersion, string walletAddress, WalletVersionStateEnum walletVersionState, string? expectedLastScannedBlockNumber = default)
        {
            CheckpointId = checkpointId;
            Network = network;
            Finality = finality;
            ManifestDigest = manifestDigest;
            PolicyDigest = policyDigest;
            ExpectedGeneration = expectedGeneration;
            ExpectedNextBlockNumber = expectedNextBlockNumber;
            ExpectedLastScannedBlockHash = expectedLastScannedBlockHash;
            ExpectedReviewRequiredAt = expectedReviewRequiredAt;
            ExpectedReviewErrorCode = expectedReviewErrorCode;
            ObservedAt = observedAt;
            WalletVersionId = walletVersionId;
            WalletVersion = walletVersion;
            WalletAddress = walletAddress;
            WalletVersionState = walletVersionState;
            ExpectedLastScannedBlockNumber = expectedLastScannedBlockNumber;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Finality
        /// </summary>
        [JsonPropertyName("finality")]
        public WalletObservationFinalityEnum Finality { get; set; }

        /// <summary>
        /// Gets or Sets WalletVersionState
        /// </summary>
        [JsonPropertyName("wallet_version_state")]
        public WalletVersionStateEnum WalletVersionState { get; set; }

        /// <summary>
        /// Gets or Sets CheckpointId
        /// </summary>
        [JsonPropertyName("checkpoint_id")]
        public Guid CheckpointId { get; set; }

        /// <summary>
        /// Gets or Sets Network
        /// </summary>
        [JsonPropertyName("network")]
        public string Network { get; set; }

        /// <summary>
        /// Gets or Sets ManifestDigest
        /// </summary>
        [JsonPropertyName("manifest_digest")]
        public string ManifestDigest { get; set; }

        /// <summary>
        /// Gets or Sets PolicyDigest
        /// </summary>
        [JsonPropertyName("policy_digest")]
        public string PolicyDigest { get; set; }

        /// <summary>
        /// Gets or Sets ExpectedGeneration
        /// </summary>
        [JsonPropertyName("expected_generation")]
        public int ExpectedGeneration { get; set; }

        /// <summary>
        /// Gets or Sets ExpectedNextBlockNumber
        /// </summary>
        [JsonPropertyName("expected_next_block_number")]
        public string ExpectedNextBlockNumber { get; set; }

        /// <summary>
        /// Gets or Sets ExpectedLastScannedBlockHash
        /// </summary>
        [JsonPropertyName("expected_last_scanned_block_hash")]
        public string ExpectedLastScannedBlockHash { get; set; }

        /// <summary>
        /// Gets or Sets ExpectedReviewRequiredAt
        /// </summary>
        [JsonPropertyName("expected_review_required_at")]
        public DateTimeOffset ExpectedReviewRequiredAt { get; set; }

        /// <summary>
        /// Gets or Sets ExpectedReviewErrorCode
        /// </summary>
        [JsonPropertyName("expected_review_error_code")]
        public string ExpectedReviewErrorCode { get; set; }

        /// <summary>
        /// Gets or Sets ObservedAt
        /// </summary>
        [JsonPropertyName("observed_at")]
        public DateTimeOffset ObservedAt { get; set; }

        /// <summary>
        /// Gets or Sets WalletVersionId
        /// </summary>
        [JsonPropertyName("wallet_version_id")]
        public Guid WalletVersionId { get; set; }

        /// <summary>
        /// Gets or Sets WalletVersion
        /// </summary>
        [JsonPropertyName("wallet_version")]
        public int WalletVersion { get; set; }

        /// <summary>
        /// Gets or Sets WalletAddress
        /// </summary>
        [JsonPropertyName("wallet_address")]
        public string WalletAddress { get; set; }

        /// <summary>
        /// Gets or Sets ExpectedLastScannedBlockNumber
        /// </summary>
        [JsonPropertyName("expected_last_scanned_block_number")]
        public string? ExpectedLastScannedBlockNumber { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WalletFencedChainReseedContext {\n");
            sb.Append("  CheckpointId: ").Append(CheckpointId).Append("\n");
            sb.Append("  Network: ").Append(Network).Append("\n");
            sb.Append("  Finality: ").Append(Finality).Append("\n");
            sb.Append("  ManifestDigest: ").Append(ManifestDigest).Append("\n");
            sb.Append("  PolicyDigest: ").Append(PolicyDigest).Append("\n");
            sb.Append("  ExpectedGeneration: ").Append(ExpectedGeneration).Append("\n");
            sb.Append("  ExpectedNextBlockNumber: ").Append(ExpectedNextBlockNumber).Append("\n");
            sb.Append("  ExpectedLastScannedBlockHash: ").Append(ExpectedLastScannedBlockHash).Append("\n");
            sb.Append("  ExpectedReviewRequiredAt: ").Append(ExpectedReviewRequiredAt).Append("\n");
            sb.Append("  ExpectedReviewErrorCode: ").Append(ExpectedReviewErrorCode).Append("\n");
            sb.Append("  ObservedAt: ").Append(ObservedAt).Append("\n");
            sb.Append("  WalletVersionId: ").Append(WalletVersionId).Append("\n");
            sb.Append("  WalletVersion: ").Append(WalletVersion).Append("\n");
            sb.Append("  WalletAddress: ").Append(WalletAddress).Append("\n");
            sb.Append("  WalletVersionState: ").Append(WalletVersionState).Append("\n");
            sb.Append("  ExpectedLastScannedBlockNumber: ").Append(ExpectedLastScannedBlockNumber).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // ExpectedGeneration (int) minimum
            if (this.ExpectedGeneration < (int)1)
            {
                yield return new ValidationResult("Invalid value for ExpectedGeneration, must be a value greater than or equal to 1.", new [] { "ExpectedGeneration" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WalletFencedChainReseedContext" />
    /// </summary>
    public partial class WalletFencedChainReseedContextJsonConverter : JsonConverter<WalletFencedChainReseedContext>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="WalletFencedChainReseedContextJsonConverter" /> class.
        /// </summary>
        public WalletFencedChainReseedContextJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// The format to use to serialize ExpectedReviewRequiredAt
        /// </summary>
        public string ExpectedReviewRequiredAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize ObservedAt
        /// </summary>
        public string ObservedAtFormat { get; private set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="WalletFencedChainReseedContext" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override WalletFencedChainReseedContext Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> checkpointId = default;
            Option<string?> network = default;
            Option<WalletObservationFinalityEnum?> finality = default;
            Option<string?> manifestDigest = default;
            Option<string?> policyDigest = default;
            Option<int?> expectedGeneration = default;
            Option<string?> expectedNextBlockNumber = default;
            Option<string?> expectedLastScannedBlockHash = default;
            Option<DateTimeOffset?> expectedReviewRequiredAt = default;
            Option<string?> expectedReviewErrorCode = default;
            Option<DateTimeOffset?> observedAt = default;
            Option<Guid?> walletVersionId = default;
            Option<int?> walletVersion = default;
            Option<string?> walletAddress = default;
            Option<WalletVersionStateEnum?> walletVersionState = default;
            Option<string?> expectedLastScannedBlockNumber = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "checkpoint_id":
                            checkpointId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "network":
                            network = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "finality":
                            finality = new Option<WalletObservationFinalityEnum?>(JsonSerializer.Deserialize<WalletObservationFinalityEnum?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "manifest_digest":
                            manifestDigest = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "policy_digest":
                            policyDigest = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "expected_generation":
                            expectedGeneration = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "expected_next_block_number":
                            expectedNextBlockNumber = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "expected_last_scanned_block_hash":
                            expectedLastScannedBlockHash = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "expected_review_required_at":
                            expectedReviewRequiredAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "expected_review_error_code":
                            expectedReviewErrorCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "observed_at":
                            observedAt = new Option<DateTimeOffset?>(JsonSerializer.Deserialize<DateTimeOffset>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "wallet_version_id":
                            walletVersionId = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "wallet_version":
                            walletVersion = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "wallet_address":
                            walletAddress = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "wallet_version_state":
                            walletVersionState = new Option<WalletVersionStateEnum?>(JsonSerializer.Deserialize<WalletVersionStateEnum?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "expected_last_scanned_block_number":
                            expectedLastScannedBlockNumber = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!checkpointId.IsSet)
                throw new ArgumentException("Property is required for class WalletFencedChainReseedContext.", nameof(checkpointId));

            if (!network.IsSet)
                throw new ArgumentException("Property is required for class WalletFencedChainReseedContext.", nameof(network));

            if (!finality.IsSet)
                throw new ArgumentException("Property is required for class WalletFencedChainReseedContext.", nameof(finality));

            if (!manifestDigest.IsSet)
                throw new ArgumentException("Property is required for class WalletFencedChainReseedContext.", nameof(manifestDigest));

            if (!policyDigest.IsSet)
                throw new ArgumentException("Property is required for class WalletFencedChainReseedContext.", nameof(policyDigest));

            if (!expectedGeneration.IsSet)
                throw new ArgumentException("Property is required for class WalletFencedChainReseedContext.", nameof(expectedGeneration));

            if (!expectedNextBlockNumber.IsSet)
                throw new ArgumentException("Property is required for class WalletFencedChainReseedContext.", nameof(expectedNextBlockNumber));

            if (!expectedLastScannedBlockHash.IsSet)
                throw new ArgumentException("Property is required for class WalletFencedChainReseedContext.", nameof(expectedLastScannedBlockHash));

            if (!expectedReviewRequiredAt.IsSet)
                throw new ArgumentException("Property is required for class WalletFencedChainReseedContext.", nameof(expectedReviewRequiredAt));

            if (!expectedReviewErrorCode.IsSet)
                throw new ArgumentException("Property is required for class WalletFencedChainReseedContext.", nameof(expectedReviewErrorCode));

            if (!observedAt.IsSet)
                throw new ArgumentException("Property is required for class WalletFencedChainReseedContext.", nameof(observedAt));

            if (!walletVersionId.IsSet)
                throw new ArgumentException("Property is required for class WalletFencedChainReseedContext.", nameof(walletVersionId));

            if (!walletVersion.IsSet)
                throw new ArgumentException("Property is required for class WalletFencedChainReseedContext.", nameof(walletVersion));

            if (!walletAddress.IsSet)
                throw new ArgumentException("Property is required for class WalletFencedChainReseedContext.", nameof(walletAddress));

            if (!walletVersionState.IsSet)
                throw new ArgumentException("Property is required for class WalletFencedChainReseedContext.", nameof(walletVersionState));

            if (!expectedLastScannedBlockNumber.IsSet)
                throw new ArgumentException("Property is required for class WalletFencedChainReseedContext.", nameof(expectedLastScannedBlockNumber));

            if (checkpointId.IsSet && checkpointId.Value == null)
                throw new ArgumentNullException(nameof(checkpointId), "Property is not nullable for class WalletFencedChainReseedContext.");

            if (network.IsSet && network.Value == null)
                throw new ArgumentNullException(nameof(network), "Property is not nullable for class WalletFencedChainReseedContext.");

            if (finality.IsSet && finality.Value == null)
                throw new ArgumentNullException(nameof(finality), "Property is not nullable for class WalletFencedChainReseedContext.");

            if (manifestDigest.IsSet && manifestDigest.Value == null)
                throw new ArgumentNullException(nameof(manifestDigest), "Property is not nullable for class WalletFencedChainReseedContext.");

            if (policyDigest.IsSet && policyDigest.Value == null)
                throw new ArgumentNullException(nameof(policyDigest), "Property is not nullable for class WalletFencedChainReseedContext.");

            if (expectedGeneration.IsSet && expectedGeneration.Value == null)
                throw new ArgumentNullException(nameof(expectedGeneration), "Property is not nullable for class WalletFencedChainReseedContext.");

            if (expectedNextBlockNumber.IsSet && expectedNextBlockNumber.Value == null)
                throw new ArgumentNullException(nameof(expectedNextBlockNumber), "Property is not nullable for class WalletFencedChainReseedContext.");

            if (expectedLastScannedBlockHash.IsSet && expectedLastScannedBlockHash.Value == null)
                throw new ArgumentNullException(nameof(expectedLastScannedBlockHash), "Property is not nullable for class WalletFencedChainReseedContext.");

            if (expectedReviewRequiredAt.IsSet && expectedReviewRequiredAt.Value == null)
                throw new ArgumentNullException(nameof(expectedReviewRequiredAt), "Property is not nullable for class WalletFencedChainReseedContext.");

            if (expectedReviewErrorCode.IsSet && expectedReviewErrorCode.Value == null)
                throw new ArgumentNullException(nameof(expectedReviewErrorCode), "Property is not nullable for class WalletFencedChainReseedContext.");

            if (observedAt.IsSet && observedAt.Value == null)
                throw new ArgumentNullException(nameof(observedAt), "Property is not nullable for class WalletFencedChainReseedContext.");

            if (walletVersionId.IsSet && walletVersionId.Value == null)
                throw new ArgumentNullException(nameof(walletVersionId), "Property is not nullable for class WalletFencedChainReseedContext.");

            if (walletVersion.IsSet && walletVersion.Value == null)
                throw new ArgumentNullException(nameof(walletVersion), "Property is not nullable for class WalletFencedChainReseedContext.");

            if (walletAddress.IsSet && walletAddress.Value == null)
                throw new ArgumentNullException(nameof(walletAddress), "Property is not nullable for class WalletFencedChainReseedContext.");

            if (walletVersionState.IsSet && walletVersionState.Value == null)
                throw new ArgumentNullException(nameof(walletVersionState), "Property is not nullable for class WalletFencedChainReseedContext.");

            return new WalletFencedChainReseedContext(checkpointId.Value!.Value!, network.Value!, finality.Value!.Value!, manifestDigest.Value!, policyDigest.Value!, expectedGeneration.Value!.Value!, expectedNextBlockNumber.Value!, expectedLastScannedBlockHash.Value!, expectedReviewRequiredAt.Value!.Value!, expectedReviewErrorCode.Value!, observedAt.Value!.Value!, walletVersionId.Value!.Value!, walletVersion.Value!.Value!, walletAddress.Value!, walletVersionState.Value!.Value!, expectedLastScannedBlockNumber.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="WalletFencedChainReseedContext" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="walletFencedChainReseedContext"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, WalletFencedChainReseedContext walletFencedChainReseedContext, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, walletFencedChainReseedContext, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="WalletFencedChainReseedContext" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="walletFencedChainReseedContext"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, WalletFencedChainReseedContext walletFencedChainReseedContext, JsonSerializerOptions jsonSerializerOptions)
        {
            if (walletFencedChainReseedContext.Network == null)
                throw new ArgumentNullException(nameof(walletFencedChainReseedContext.Network), "Property is required for class WalletFencedChainReseedContext.");

            if (walletFencedChainReseedContext.ManifestDigest == null)
                throw new ArgumentNullException(nameof(walletFencedChainReseedContext.ManifestDigest), "Property is required for class WalletFencedChainReseedContext.");

            if (walletFencedChainReseedContext.PolicyDigest == null)
                throw new ArgumentNullException(nameof(walletFencedChainReseedContext.PolicyDigest), "Property is required for class WalletFencedChainReseedContext.");

            if (walletFencedChainReseedContext.ExpectedNextBlockNumber == null)
                throw new ArgumentNullException(nameof(walletFencedChainReseedContext.ExpectedNextBlockNumber), "Property is required for class WalletFencedChainReseedContext.");

            if (walletFencedChainReseedContext.ExpectedLastScannedBlockHash == null)
                throw new ArgumentNullException(nameof(walletFencedChainReseedContext.ExpectedLastScannedBlockHash), "Property is required for class WalletFencedChainReseedContext.");

            if (walletFencedChainReseedContext.ExpectedReviewErrorCode == null)
                throw new ArgumentNullException(nameof(walletFencedChainReseedContext.ExpectedReviewErrorCode), "Property is required for class WalletFencedChainReseedContext.");

            if (walletFencedChainReseedContext.WalletAddress == null)
                throw new ArgumentNullException(nameof(walletFencedChainReseedContext.WalletAddress), "Property is required for class WalletFencedChainReseedContext.");

            writer.WriteString("checkpoint_id", walletFencedChainReseedContext.CheckpointId);

            writer.WriteString("network", walletFencedChainReseedContext.Network);

            var finalityRawValue = WalletObservationFinalityEnumValueConverter.ToJsonValue(walletFencedChainReseedContext.Finality);
            writer.WriteString("finality", finalityRawValue);

            writer.WriteString("manifest_digest", walletFencedChainReseedContext.ManifestDigest);

            writer.WriteString("policy_digest", walletFencedChainReseedContext.PolicyDigest);

            writer.WriteNumber("expected_generation", walletFencedChainReseedContext.ExpectedGeneration);

            writer.WriteString("expected_next_block_number", walletFencedChainReseedContext.ExpectedNextBlockNumber);

            writer.WriteString("expected_last_scanned_block_hash", walletFencedChainReseedContext.ExpectedLastScannedBlockHash);

            writer.WriteString("expected_review_required_at", walletFencedChainReseedContext.ExpectedReviewRequiredAt.ToString(ExpectedReviewRequiredAtFormat));

            writer.WriteString("expected_review_error_code", walletFencedChainReseedContext.ExpectedReviewErrorCode);

            writer.WriteString("observed_at", walletFencedChainReseedContext.ObservedAt.ToString(ObservedAtFormat));

            writer.WriteString("wallet_version_id", walletFencedChainReseedContext.WalletVersionId);

            writer.WriteNumber("wallet_version", walletFencedChainReseedContext.WalletVersion);

            writer.WriteString("wallet_address", walletFencedChainReseedContext.WalletAddress);

            var walletVersionStateRawValue = WalletVersionStateEnumValueConverter.ToJsonValue(walletFencedChainReseedContext.WalletVersionState);
            writer.WriteString("wallet_version_state", walletVersionStateRawValue);

            if (walletFencedChainReseedContext.ExpectedLastScannedBlockNumber != null)
                writer.WriteString("expected_last_scanned_block_number", walletFencedChainReseedContext.ExpectedLastScannedBlockNumber);
            else
                writer.WriteNull("expected_last_scanned_block_number");
        }
    }

    /// <summary>
    /// The WalletFencedChainReseedContextSerializationContext
    /// </summary>
    [JsonSourceGenerationOptions(WriteIndented = true, GenerationMode = JsonSourceGenerationMode.Metadata | JsonSourceGenerationMode.Serialization)]
    [JsonSerializable(typeof(WalletFencedChainReseedContext))]
    public partial class WalletFencedChainReseedContextSerializationContext : JsonSerializerContext { }
}
