<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo> <!-- setting GenerateAssemblyInfo to false causes this bug https://github.com/dotnet/project-system/issues/3934 -->
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>X402Api</AssemblyName>
    <PackageId>X402Api</PackageId>
    <OutputType>Library</OutputType>
    <Authors>x402api</Authors>
    <Company>x402api</Company>
    <AssemblyTitle>x402api .NET SDK</AssemblyTitle>
    <Description>Official .NET SDK for the x402api public API</Description>
    <Copyright>No Copyright</Copyright>
    <RootNamespace>X402Api</RootNamespace>
    <Version>1.3.0</Version>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\X402Api.xml</DocumentationFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/x402api-com/x402api-dotnet.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReleaseNotes>Minor update</PackageReleaseNotes>
    <Nullable>enable</Nullable>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" Condition="'$(TargetFramework)' == 'net8.0'" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Condition="'$(TargetFramework)' == 'net8.0'" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Condition="'$(TargetFramework)' == 'net8.0'" Version="8.0.20" />
    <PackageReference Include="Microsoft.Net.Http.Headers" Condition="'$(TargetFramework)' == 'net8.0'" Version="8.0.17" />
  </ItemGroup>

</Project>
